### ISSUE TITLE
Please consider using JS (ES6) instead of coffeescript

### ISSUE THREAD

**Issue by MarkusRehberg** [GetmeUK/ContentTools#10]
What a nice project. Unfortunately most people don't want to learn a not common, not standardized language (coffee script), nor do they want to have to transpile for grasping it etc., when JS is used by everybody and works perfectly fine, especially now with ES6. I think this will hurt your project, prevent it from getting the attention it deserves, which is sad. In other words: Please use standards wherever possible.

**Comment by anthonyjb** [comment]
I will certainly consider it. Oddly enough I'm not a git user for the most part, my version control tool of preference is Mercurial, but I know that most people out there prefer git and so I sold out ;)

I don't want to get into a debate about ES6 vs CoffeeScript or any other transpiler, I use CoffeeScript because I like it's concise appearance (I use MoonScript for Lua for a similar reason). I find it very simple to switch between the two and have provide code examples in both JS and CoffeeScript.

The libraries themselves can be used with JavaScript and documentation is provided, but if you wish to contribute code to the library and haven't used CoffeeScript before or don't like it then I accept that's a barrier. Building the project is pretty simple though `grunt build/watch`, and I'm guessing you'd have no objection to SASS over CSS. 

So I have to be honest and say it's not a high priority for me now - but I will reconsider once ES6 is more fully supported by all the target browsers (https://kangax.github.io/compat-table/es6/).

As for your statements about CoffeeScript and most people; that may well be true but I don't mind if the project introduces more people to CoffeeScript who might otherwise not be aware of it, even it they don't like it. From my personal stand point CoffeeScript is a joy to use :)

**Comment by MarkusRehberg** [comment]
Thanks for your polite answer! Actually, after reading my onw request, I should have formulated it equally polite. The most important thing is, that you enjoy working on your project. Lucilly, ES6 has adopted many concepts of CoffeeScript (somehow proving the point of CoffeeScript). Regarding browser-support, you may just replace the CoffeeScript-transpiler by babel, typescript etc., but I am sure you know all this better than me. So anyhow, thanks again for this great project!

**Comment by anthonyjb** [comment]
Thanks @MarkusRehberg :+1:

**Comment by edwinyzh** [comment]
I also wish this very well written and well documented lib is in javascript :)

**Comment by K12AZ** [comment]
sad

**Comment by anthonyjb** [comment]
The design decision for CT2 is that we are using JavaScript ES6 (with webpack and Babel). This is my day-to-day frontend development environment now so it's what I'm most comfortable with.
