### ISSUE TITLE
Support for html widgets

### ISSUE THREAD

**Issue by andtii** [GetmeUK/ContentTools#102]
It would be nice to add support to the api so its possible to have a library of widgets / templates so that the user can drag an item from a widget gallery and drop it inside a content area. Today you can only drag & drop between existing content areas but it would be nice to add support to drag items from an library of predefined html and then drop it directly onto the content area.

**Comment by anthonyjb** [comment]
Hi @andtii - this is something that is in the pipeline (though it's a long pipeline right now), it's a feature request that's popular and has been discussed in more detailed previously here https://github.com/GetmeUK/ContentTools/issues/13 (I think perhaps we should change the title of the issue to be more appropriate).

The idea is to create a ContentFlow library that allows for dynamic creation/management of the editable regions within a page from templates.

I'm going to mark this as a duplicate for now an close it but only because I just want the one issue regarding it open - and I realise that the existing issue wouldn't be very apparent currently so that needs to change.

Thanks for your interest :+1:  in CT

Duplucate of #13
