### ISSUE TITLE
Mootools introduces JS code in the br tag

### ISSUE THREAD

**Issue by etlel** [GetmeUK/ContentTools#121]
The presence of Mootools (1.4 to 1.6 tested on Chrome and Firefox) introduces JS code in the BR tag. The JS code may remain unobserved as it fits as an attribute of BR. It is possible to visualize the mess by using the code editor UI.

Happens in two occasions : 1. Clean code is loaded and contains BR that comes contamined when loading it with the Editor. 2.Contamined BR tag is inserted by the Breakline tool.

This not occurs when removing Mootools of the scripts called.

~~Another bug, independant of Mootools, is affecting the Breakline tool : It must be clicked twice when trying to add a breakline at the last position of the editable field.~~

![sourcejs](https://cloud.githubusercontent.com/assets/17115179/12877362/237250c0-cde0-11e5-99bc-1eff635a90e7.png)

**Comment by anthonyjb** [comment]
Thanks for reporting this @etlel, I'm going to look in to the mootools issue now.

Re. the other issue you reported I believe this is purely a difference in browser behaviour to what you are expecting. If you insert a newline at the end of a block of content the <br> is inserted (you can see if you inspect the element but the browser may not create a newline or move the cursor. If you start to type the content will however appear on a newline.

**Comment by anthonyjb** [comment]
OK looking into this the cause of the issue I could do with some help from anyone who is more experienced/familiar with mootools. As far as I can tell mootools adds custom attributes to DOM elements (such as $constructor="...") so that when `innerHTML` is used to sync content on inside the DOM with the editable element representing it these attributes are captured.

I can't find any documentation or stackoverflow issues on how to disable this behaviour so whilst the approach by mootools seems odd to me I suspect that I'm missing something obvious or that someone more experienced with mootools will know the answer.

**Comment by anthonyjb** [comment]
Bugs keep me up at night :( and this one had been here too long - so I decided this weekend I needed to sit down for a few hours with the mootools code base open and track the issue down.

**The issue had nothing to do with mootools** it was actually an issue in the HTMLParser library that was resetting the attributes store in the parser to a list instead of an object. As mootools extends the native list object and because my code was expecting an object, the mootools extensions to the list object got added as attributes to the node (you can see the fix here https://github.com/GetmeUK/HTMLString/commit/5fbd0a9e8f21c5427d5842bff3912b4ca8f04dc0).

So in closing it was my fault, it's not fixed and I'll sleep better this week :)
