### ISSUE TITLE
Youtube z-index issue with IE

### ISSUE THREAD

**Issue by etlel** [GetmeUK/ContentTools#122]
Fix a z-index problem affecting the display of Youtube videos on Internet Explorer.

[Bug documented here](http://stackoverflow.com/questions/5281002/z-index-and-iframes)

[youtube-z-index-patch.txt](https://github.com/GetmeUK/ContentTools/files/121050/youtube-z-index-patch.txt)

**Comment by anthonyjb** [comment]
Having read into `wmode` a bit more (thank you for the stackoverflow link :+) I'm not currently comfortable fixing the value set for this as there are a number of modes each with different trade performance characteristics.

However, prior to you reporting this issue setting a video URL for youtube or vimeo stripped all parameters from the URL inserted. This behaviour has now been changed so that the params are maintained allowing the user to specify the URL parameters required for the video when they add it.

In some situations a default of `wmode=transparent` would likely be beneficial (e.g with a user base unlikely to use this understand that they need to add this. In this scenario one approach would be to listen for the `attach` event against the ContentEdit root, checking the URL to see if it contains a wmode value and then adding one if not (something like), this way existing youtube videos will have the default set as soon as the page is edited:

```coffeescript
ContentEdit.Root.get().bind 'attach', (elm) ->
    
    # We're only interested in videos
    if elm.typeName() != 'Video'
        return

    # Has `wmode` already been set
    if elm.attr('src').indexOf('wmode') > -1
        return

    # No wmode set so add a default
    if elm.attr('src').indexOf('?')
        elm.attr('src', elm.attr('src') + '&wmode=transparent')
    else
        elm.attr('src', elm.attr('src') + '?wmode=transparent')

```

**Comment by etlel** [comment]
Thank you for the commit and the snippet. Here is JS code that worked for me. Im posting it beause It took me a while to find the missing loop.

```javascript
	ContentEdit.Root.get().bind('attach', function (elm){
		elm.descendants().forEach(function(elmm){
			if(elmm.typeName() != 'Video') return;
			if(elmm.attr('src').indexOf('wmode') > -1) return;
			if(elmm.attr('src').indexOf('?')) return elmm.attr('src', elmm.attr('src') + '&wmode=transparent');
			else return elmm.attr('src', elmm.attr('src') + '?wmode=transparent');
		});
	});
```
