### ISSUE TITLE
Undo-ing to the beginning blurs the element

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#129]
Replicate:

* Type something
* Drag and drop something
* Undo twice - in the last undo, the element becomes blurred and now prevents the redo from being clicked unless an element is clicked again.

**Comment by anthonyjb** [comment]
I think at the moment unto is just unavailable if an element isn't focused will look at that.

**Comment by anthonyjb** [comment]
So I've fixed this issue here by allowing tools to be flagged as not requiring elements to be applied. Undo/Redo tools are kind of an exception here. To allow a tool to be used even if no element is currently selected/focused the tool must now have the class variable `@requiresElement = false` set (the default is now `true` for tools).

In addition to this bug I also noticed that the code which checks to see if tools need to be updated was a.) incorrect and b.) the output was being ignored anyway. So I have now fixed this issue (which should be good for performance at least) however given it was always updating before we may see some unforeseen side affects - tests are passing but the suite is not complete yet so not that helpful - I've played around with it and it seems correct but anyone spotting an issue please let me know.

**Comment by bfintal** [comment]
Haven't tried the new change yet. I've been extending a lot of aspects of CT extensively, I'll check if the updater thing has some negative impact :)
