### ISSUE TITLE
`style` is not in the restricted_attributes list, nor is `onclick`, `id` et al.

### ISSUE THREAD

**Issue by Qqwy** [GetmeUK/ContentTools#133]
The `style` attribute is not in the default restricted_attributes list, which would enable users to e.g. absolutely position elements where they are not supposed to go.

I think it would be a sensible default to add this attribute to the ContentTools.RESTRICTED_ATTRIBUTES list.

It also seems to be able to override the element's `id` and `class` by specifying these as well.

The same is true for JS-injection possibilities like `onclick`, `onhover`, `onkeydown`, `onload`, etc., which opens up interesting XSS-possibilities.

I think you'll agree that this is an important issue that needs to be fixed.

**Comment by anthonyjb** [comment]
Hi @Qqwy,

The list of restricted attributes can be set by the developer implementing the tool as to what they feel is appropriate, allowing `class` and `id` to be set against an element is something I would always want to be able to do (but not everyone will of course which is why it can be configured). Setting an `id` for example is a how I'm able to link to sections within a page from links, without this option that facility wouldn't be possible.

As for JavaScript options I agree I think this might be something worth considering as its potential not good practice to set behaviours inline like this - **but there is no basis for the change on the grounds of security**. 

The JavaScript can play no role in securing your website and this is something you must do server-side when saving the code. There are any number of ways that the output from ContentTools which is then posted to the server can be modified client-side and you cannot consider the content you receive safe.

For the most part if you're implementing ContentTools as a tool used by trusted users (e.g editors updating their own website from a password protected area) then the level of trust you apply to the content you accept from users will be relatively high, if you're allowing CT to be used by public users and saving the output (or for that matter saving any input from a user that will then be rendered back as unescaped html) you should ensure treat it with a very health dose of scepticism and you nullify any possible threats server-side.

This is getting a little beyond the scope of CT though now so I'll end on that note.

**Comment by Qqwy** [comment]
Hello @anthonyjb ,

After considering this for a bit, I have to agree with you. When dealing with very trusted users, such as a user editing their own site, they should not be limited. And because there is the option to add/change this behaviour, it is good as it is.

And yes, proper validation should always happen server-side. 

Thank you for pointing out the flaw in my train of thought.

**Comment by Qqwy** [comment]
Is there a possibility to restrict attributes on *every* element right now? The ContentTools.RESTRICTED_ATTRIBUTES hash is nested by tag name.

**Comment by anthonyjb** [comment]
Hi @Qqwy, there is no way currently to set a wildcard for matching tags against restricted attributes.
