### ISSUE TITLE
Handling images inside p

### ISSUE THREAD

**Issue by BugHunter2k** [GetmeUK/ContentTools#139]
Hi, 

when placing an image inside an p-Tag the image can't be moved. Made a quick pen for illustration:
http://codepen.io/BugHunter2k/full/ZQdNGy/

is this by design or is this a  bug?

**Comment by anthonyjb** [comment]
Hi @BugHunter2k images within paragraphs are not part of the editable environment, rather they are content within the editable paragraph - so not being able to drag-drop them around in the same way as editable images is by design (is as much that I've not looked at implementing that to date - but if it's a popular request I'd happily look into it).

If you're stuck for a short term solution you can move the image within the code by using the code section of the properties dialog.
