### ISSUE TITLE
Best way to customize ContentTools native behavior 

### ISSUE THREAD

**Issue by Eeliya** [GetmeUK/ContentTools#145]
For example I want to change the behavior of Image element completely.

**What would be the best way to do that?**

**Comment by anthonyjb** [comment]
Hi @Eeliya this question is a little too open, to be able to answer it would be useful if you could define what it is you're looking to achieve by changing the behaviour.

**Comment by Eeliya** [comment]
For example, the Image element use a div with background-image to represent the image in the edit mode. I want to change that and use a **img** tag instead of **div** tag.

**Comment by anthonyjb** [comment]
OK so replacing the `div` tag with an `img` tag could be a little painful purely because we use pseudo elements (`:before` and `:after`) to show information about the image.

However you could try using an `img` tag and then applying the following method to make it support pseudo elements: http://stackoverflow.com/questions/5843035/does-before-not-work-on-img-elements (the answer starting **I found a way to make this work in pure css**).

If that does work you'd just need to change the `mount` method (https://github.com/GetmeUK/ContentEdit/blob/master/src/scripts/images.coffee#L62) to output an `img` and set the source instead of the background.

**Comment by Eeliya** [comment]
Alright,

Because I do not want to change the mount method of ContentEdit.Image, I copied the ContentEdit.Image class and add my changes to it and loaded after the ContentTools is loaded.

So I overwrite ContentEdit.Image completely with my custom version of it.

**Comment by anthonyjb** [comment]
That approach would work too :)

**Comment by Alex360hd** [comment]
Could you please share your code that replace a div with background with an img tag to deal with images in content tools ?

I'm also interested as my website is responsive design, the background method is not appropriate at all to handle this.
