### ISSUE TITLE
changing region html programaticly works, but not with Promise ...

### ISSUE THREAD

**Issue by Cyrille37** [GetmeUK/ContentTools#151]
Hi,
Just after clicked on blue edit button I want to change the editable element's html.

**It works** with a synchronous code : 
```javascript
    var editor = ContentTools.EditorApp.get();
    editor.init('*[data-editable]', 'data-name');
    var editorCls = ContentTools.EditorApp.getCls();
    editor.start = function () {
      $(editor.domRegions()).each(function(idx, item){
        $(item).html('<p>coucou</p>');
      });
      editorCls.prototype.start.call(editor);
    });
```
But **it does not work** while using Promise:
```javascript
    var editor = ContentTools.EditorApp.get();
    editor.init('*[data-editable]', 'data-name');
    var editorCls = ContentTools.EditorApp.getCls();
    editor.start = function () {
      var calls = new Array();
      $(editor.domRegions()).each(function(idx, item){
        calls.push( $.get('/resource/'+$(item).attr('data-name'))
        .done(function( data ) {
          // data = '<p>coucou</p>'
          $(item).html( data );
        }));
      });
      $.when( calls ).then( function(){
        editorCls.prototype.start.call(editor);	    
      })
    });
```

**Comment by anthonyjb** [comment]
Hi @Cyrille37 does the console report any errors?

**Comment by Cyrille37** [comment]
Hey ;-)
No error, all is so nice.
With the use of Promise, visually the text change but when opening the properties window, in the "code"  tab,  I can see the initial content.

**Comment by anthonyjb** [comment]
OK if you change the content of the HTML before calling start against the editor (e.g `editor.start()`) then since the HTML is parsed directly from the DOM that should work so it seems like the content is being changed after start has been called.

It's a fair while since I've used JQuery so I maybe way off base here (forgive me if so), but looking at the documentation [here](https://api.jquery.com/jquery.when/), I'm not sure done should be called like this against each `$.get`, e.g from the docs calling `$.ajax` multiple times:

```javascript
$.when( $.ajax( "/page1.php" ), $.ajax( "/page2.php" ) ).done(function( a1, a2 ) {
  // a1 and a2 are arguments resolved for the page1 and page2 ajax requests, respectively.
  // Each argument is an array with the following structure: [ data, statusText, jqXHR ]
  var data = a1[ 0 ] + a2[ 0 ]; // a1[ 0 ] = "Whip", a2[ 0 ] = " It"
  if ( /Whip It/.test( data ) ) {
    alert( "We got what we came for!" );
  }
});
```

There's nothing in the start editing process I can think of that would break the promise chain like you're describing, like your first example the parsing of the DOM into the editable set of elements is a synchronous process.

One other thing to try perhaps is logging to the console in the `done` methods and the `then` method in your example so that you can see the order of things in the console.

**Comment by Cyrille37** [comment]
mmmhhh... U're right.
Thanks a lot for ur support ;-)

**Comment by anthonyjb** [comment]
No problem :)

**Comment by Cyrille37** [comment]
U saved me ;-)

The right solution was `$.when.apply(null,calls).then( ...` with the `apply()` to transform the array in arguments list.

```javascript
editor.start = function ()
{
	var calls = new Array();
	$(editor.domRegions()).each(function(idx, item){
	    calls.push( $.get({url:'/resource/'+$(item).attr('data-name'), context:{item:item}})
	    .done(function( data ) {
		    // console.log('changing '+$(this.item).attr('data-name'));
		    $(this.item).html( data );
	    }));
	});
	$.when.apply(null,calls).then( function(){
	    // console.log('Editing !');
	    ContentTools.EditorApp.getCls().prototype.start.call(editor);
	})
};
```
