### ISSUE TITLE
Span Element

### ISSUE THREAD

**Issue by shockdot** [GetmeUK/ContentTools#155]
Is it possible to implement a span element so that I can assign custom classes to said element by clicking the "span" button on the bottom left of the screen?

I want something like this to be possible...

`<p>Some text <span class='SpanText'>goes here</span>.</p>`

Using existing tools as examples im able to make the p tag get replaced by span... But I would like to be able to add a span element to areas in the p element so that I can change text color like that.

Is this possible, and is an example available?

**Comment by anthonyjb** [comment]
Hi @shockdot, at the moment the inspector doesn't show tags which are children of editable elements and the properties dialog isn't set up to support modifying non-editable elements. 

This is something I believe some one could look at implementing as the `HTMLString` library provides tools that make inspecting the content pretty easy.

At the moment the only way you can do this via the CT editor is to use the properties dialog and then modify the inner code directly. I don't think currently I'd want to consider this as a core library feature but if it was available as an extension I'd happily promote/link to it.

**Comment by anthonyjb** [comment]
Just on looking at places you might start you might want to check out the tutorial on adding a new tool which covers inserting time tags inside of content elements http://getcontenttools.com/tutorials/adding-new-tools

This is at least would allow you to insert and modify a span with plus it's class via the toolbox, though it doesn't cover integrating this into the inspector bar, there's no existing tutorial around the inspector bar but if you get some code together and need a hand at any point give me a shout :)

**Comment by shockdot** [comment]
I've gone through that guide, problem being I don't know how to hook into the Inspector :/. But by the sounds of it, there's not even a similar example to accomplish what I want haha...

**Comment by shockdot** [comment]
I've managed to just make a Properties tool, which is great then I can just use this tool when I want with my sub tags (such as span, bold, i).

However, the main issue still arises... Which is it gets the root element and not the current actively selected element... So when I open the properties window it opens with the root element.... Is there no way to get the currently selected element in the @apply function.... Maybe by somehow using the element, and selection variables together?

**Comment by anthonyjb** [comment]
Hi @shockdot - by root element I presume you're describing the parent element e.g the `<p>` tag or `ContentEdit.Text` element not the `ContentEdit.Root` element? If that's the case then that would be the expected behaviour, the child elements your describing here aren't part of the editable DOM tree (e.g Region > Text) and so the inspector and properties dialog are not designed to interact with them.

To change this behaviour is not a small undertaking but I can highlight where you'd need to look:

- The `updateTag` method for the inspector bar needs to be updated to add inline tags from elements with content, to do this you'll need to select the character the carat is against in the content and then loop through the tags applied to that content.
    - https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/ui/inspector.coffee#L53
    - http://getcontenttools.com/api/content-select (to get the current carat position look at `ContentSelect.Range.query(element)` where element in this case is `element.domElement()`)
    - http://getcontenttools.com/api/html-string (to get the current list of sub tags you'll want to use `element.content.children[caratIndex].tags()`)

- The `TagUI` class will have to be updated to accept inline tags, I would still send through the parent editable element here but also include the sub tag which should then be used to display in the tag itself as well as being passed to the properties dialog. You will also need to update the save event for the properties dialog here to cater for changes being applied to the inline element and not the editable element.
    - https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/ui/inspector.coffee#L86
    - https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/ui/inspector.coffee#L142

- Finally you'll need to up date the properties dialog to accept an inline element, again I would still send the parent editable element through. There's quite a few changes need making here to how it queries for information about the element but for the most part it would just be checking to see whether an inline element has been provided and using that instead of the parent editable element if so.
    - https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/ui/dialogs/properties.coffee#L1
