### ISSUE TITLE
Show toolbar only on focus

### ISSUE THREAD

**Issue by markusvt** [GetmeUK/ContentTools#168]
Is it possible to show the toolbar and the inscpector only if an editable area has focus of the user?

My scenario is the following:
I have a formular that consists of several normal input elements and also some areas where the user can edit HTML. If the user works with the normal input elements, i dont want to display the toolbox etc. as it will only confuse the user. So ideally I would like to show the toolbar when a user sets the focus inside an editable area and hide them when that area looses focus.

I already tried something with the "focusin" and "focusout" JQuery events, but that doesnt work when the user starts the drag & drop functionality (looses focus at the drag moment)

**Comment by anthonyjb** [comment]
Hmmm... this is a good question, part of the issue is that ContentEdit elements have their mechanism for focus and blur because some of the elements you manage with ContentTools aren't designed to receive focus natively.

One option would be to run a function periodically that simply checked whether the element that has focus is one of the inputs where you want the box hidden (using a class check for `hide-toolbox` perhaps), for example:

```JavaScript
var toolboxMonitor = function() {
    var focused = document.activeElement;
    if (focused) {
        if (!focused.classList.contains('hide-toolbox')) {
            ... hide the toolbox
        } else {
            ... show the toolbox
        }
    } else {
    }
}
setInterval(toolboxMonitor, 250)
```
