### ISSUE TITLE
How to make new element editable ?

### ISSUE THREAD

**Issue by l2aelba** [GetmeUK/ContentTools#186]
I trying hard to find API / Events on docs, but still no luck. so please help :D

**HTML :**

```html
<div id="edit">
   <div data-ce><p>Hello</p></div>
</div>
```

**JS :** 

```javascript
var editor;
var addIds = function() {
	var domRegions = document.querySelectorAll('[data-ce]');
	for(var i = 0; i < domRegions.length; i++) {
		var domRegion = domRegions[i];
		domRegion.setAttribute('data-ce',i);
	}
};

var EditorSetup = function() {
	editor = ContentTools.EditorApp.get();
	editor.init('[data-ce]','data-ce');
};


addIds();
EditorSetup();

// I adding new element when editor is started
editor.start();

// Try to add new element
$('#edit').append('<div data-ce><p>World</p></div>'); // How to make this editable ?

```

Thanks

**Comment by l2aelba** [comment]
I think I got it. But not sure this is correct way to do :

```javascript
var $new_element = $('<div data-ce><p>World</p></div>');
$('#edit').append($new_element);

var new_region = new ContentEdit.Region($new_element.find('[data-ce]')[0]);
editor._domRegions = document.querySelectorAll('[data-ce]');
```

**Comment by l2aelba** [comment]
Nahhh i think this should work :

```javascript
editor.destroy();
addIds();
EditorSetup();
editor.start();
```

**Comment by anthonyjb** [comment]
@l2aelba can I confirm you solved your issue?

**Comment by l2aelba** [comment]
@anthonyjb Yep, But I need some feedback :D

**Comment by anthonyjb** [comment]
OK I'm not entirely sure from your what you're attempting to do but if you want to perform an action when the editor is started you could listen for the start event (documented here: http://getcontenttools.com/api/content-tools#editor-app)

```JavaScript
editor.addEventListener('start', function (ev) {
    ...add your new elements...
});
```

However this wont directly solve the issue because your adding new content to the page that the editor doesn't know about (the editor selects DOM regions when the `init` method is called), to solve that you'd need to do the following:

```JavaScript
editor.addEventListener('start', function (ev) {
    ...add your new elements...
    @_domRegions = document.querySelectorAll('[data-ce]');
});
```

However this will occur each time the editor is started (so new content will be created each time the edit button is clicked), so if you just want the editor to look for new editable regions whenever the edit button is clicked then you could just do:

```JavaScript
editor.addEventListener('start', function (ev) {
    @_domRegions = document.querySelectorAll('[data-ce]');
});
```

**Comment by l2aelba** [comment]
Aha ok solved for me :D thanks so much
