### ISSUE TITLE
Multiples tags

### ISSUE THREAD

**Issue by jonathandion** [GetmeUK/ContentTools#188]
Hi,

I have multiple data-editable attributes and every time I click on the edit button (pencil) there is a tons of auto generated p tag before and after each data-editable elements. It's normal ?

Thanks.

**Comment by anthonyjb** [comment]
Hi @jonathandion - your going to have to provide a bit more information I'm afraid, can you provide a copy of the HTML before the edit button is clicked and after?

**Comment by jonathandion** [comment]
@anthonyjb sure

    <div data-editable="" data-name="Project_LongDesc">
        <p class="ce-element--empty ce-element ce-element--type-text"></p>
        <p class="ce-element--empty ce-element ce-element--type-text"></p>
        <p class="ce-element--empty ce-element ce-element--type-text"></p>
        <p class="ce-element ce-element--type-text">asas</p>
        <p class="ce-element--empty ce-element ce-element--type-text"></p>
        <p class="ce-element--empty ce-element ce-element--type-text"></p>
        <p class="ce-element--empty ce-element ce-element--type-text"></p>
    </div>

**Comment by anthonyjb** [comment]
@jonathandion is this before or after?

**Comment by jonathandion** [comment]
@anthonyjb after the click

**Comment by anthonyjb** [comment]
OK can you send the HTML before and your code to initialize the editor?

**Comment by jonathandion** [comment]
@anthonyjb 
    <div data-editable="" data-name="Project_LongDesc">
        <p></p>
        <p>test</p>
        <p></p>
    </div>

**Comment by jonathandion** [comment]
@anthonyjb  thanks for the help ! I have another question how to know if the editor is ready ? There is no callback like this :

```editor.isReady(function() {
// do some stuff here
})```

and what is the best way to show the the toolbox directly on load ? Right now I'm using the JQuery trigger() function.

Thanks !

**Comment by anthonyjb** [comment]
Thanks - looks like it may not be coping with the empty <p> tags I'll take a look and see if I can reproduce.

**Comment by anthonyjb** [comment]
@jonathandion ok so re. the issue you're reporting I can't reproduce this I'm afraid - I've copied the before HTML you sent me into the sandbox HTML example provided in the library it works as expected and shows the correct number of paragraph tags so my best guess is that somehow something is getting duplicated as part of your integration code. I'm happy to keep looking and to concede it maybe a bug with the library but at this point I need more also, ideally I need you to reproduce the error using the sandbox example and send me the code so I can reproduce the error for myself and track down the problem code.

Re. your question regarding callbacks the editor is set to ready once the `init` method is called and when stopped (via the `stop` method), I'm happy to consider adding a `init` event for the editor so that you can bind to it using the `addEventListener` (there is already a `stop` event) but would like to understand what you're are trying to achieve a little better before I recommend a solution.

**Comment by jonathandion** [comment]
@anthonyjb thanks allot for your time. 

The reason I need a callback it's because i'm trying to target some elements from the plugin. I'm actually targeting my elements after the init function but the length is 0. I'm using a setTimeout or setInterval to check if 'editor.isReady()' and then I can manipulate the DOM. Like I said, I trigger a 'click' on the edit button to show the toolbox without clicking on it. I would like to know if there is a better way to do this.

Thanks.

**Comment by anthonyjb** [comment]
@jonathandion instead of triggering a click against the ignition switch you could call `start` against the editor and manually change the state of the switch, for example:

```JavaScript
editor.start();
editor.ignition().state('editing');
```

Would that help?

**Comment by jonathandion** [comment]
Thanks @anthonyjb it's working like the trigger but I still need to wrap it in a setTimeout because sometimes it triggered sometime not. No a big issue.

**Comment by anthonyjb** [comment]
Hi @jonathandion thanks for your input, can you describe when it triggers and when it doesn't? I'd like to identify if there's something that can be done to improve things here.
