### ISSUE TITLE
<Br> tag

### ISSUE THREAD

**Issue by SimBioT1954** [GetmeUK/ContentTools#205]
How does `<br>` tag works in the **ContentTools**? It dissappear when I click "save".

**Comment by anthonyjb** [comment]
Hi @SimBioT1954,

Line breaks / `<br>` tags may disappear if they are positioned at the start or the end of a block of text (other than pre-formatted text, e.g `<pre>` tags). This is because white-space is trimmed/stripped from the end of text block by default in ContentTools. There is a discussion regarding this behaviour here: https://github.com/GetmeUK/ContentTools/issues/113 and a related stackoverflow post detailing an approach to modify this behaviour should you wish to here: https://stackoverflow.com/questions/36883079/how-to-preserve-multiple-br-when-no-content-before-or-after-with-contenttools/36954440#36954440
