### ISSUE TITLE
Unable to editor.init with NULL content

### ISSUE THREAD

**Issue by oodavid** [GetmeUK/ContentTools#216]
I want to initialise the editor where there are no editable areas on the DOM (yet). My editable areas are created on an ad-hoc basis. As it stands the editor state remains "dormant" even after I add new editable areas and call `editor.syncRegions(...);`.

I'll post a demo of what I'm making on gitter so you can get a little more context :)

A bit of an odd edge-case, so apologies in advance!

**Comment by anthonyjb** [comment]
Hi @oodavid - when you say the editor remains dormant are you referring to the state attribute of the editor (e.g `isDormant()` returns `True`) or is it just that the editor button is not displayed?

If it's the latter then this is because if the length of DOM elements selected is 0 initially the editor doesn't create the edit buttons - this is actually something that needs to be addressed moving forward with the `syncRegions` method so I'll mark this as an enhancement that I'll look to introduce in the next release.

I think in either case as a simple short term option if you simply `destroy` and `init` the editor when goinf from no regions to some regions this will solve the problem.

**Comment by anthonyjb** [comment]
OK so basically the previous releases would bail when there were no regions defined effectively preventing the editor leaving the `DORMANT` state as you specified. I've modified the `init` method now to always initialize the editor `syncRegions` is now responisble for hiding or showing the ignition switch depending on whether or not their are any regions defined.

The fix will be pushed shortly in release 1.2.6.
