### ISSUE TITLE
Looks Very Cool, but the Demo isn't Functional

### ISSUE THREAD

**Issue by queejie** [GetmeUK/ContentTools#219]
Highlighting words on the demo page and trying to change them to bold or italic, or changing justification doesn't work on a Mac, in the latest Chrome, Safari or Firefox.  The only thing that did happen was when I chose to convert the paragraph to a bullet list, it changed the font to very small and the color to gray.  Clicking the bullets again did not undo that. I'm guessing there is just something wrong with the installation on the demo page.

**Comment by anthonyjb** [comment]
Hi @queejie - my guess is that your changing the text in the opening paragraph (white text on blue), if this is the case then basically the reason is I use a reset style sheet for the website and haven't defined styles for the bold, italic or list items within the upper section of the site (e.g the text in blue). If you try again and modify text within the main article (e.g the white section) these styles should work fine.

You can modify the behaviours and tools available based on the selected element so as this feature becomes more established I'll look to use it to prevent this confusion moving forward.

If this isn't the case do let me know and I'll look into the issue further.

**Comment by queejie** [comment]
Yes, that's it.  The layout led me to believe I was editing the top, blue portion of the page.  When the two items weren't apparently editable, it seemed as though it wasn't functional.

Thank you for your rapid response!
