### ISSUE TITLE
Add new row indicator

### ISSUE THREAD

**Issue by a-komarev** [GetmeUK/ContentTools#222]
The main idea - to have a 'ghost' row in each region which will displays that user can add a new row. By clicking on it new text node will be appended to the region.

### Use cases

* When user opens page with content editor but there is no data in it yet (it's hard to understand that you can edit something here if there is blank white page).
* Case #91 `create a new paragraph after uploading images` described earlier.

### Some thoughts on behavior

* Don't add new rows if bottom ones is empty. Just focus caret on it.
* Have an ability to disable\enable this behavior.
* Fixtures requires placeholders and shouldn't have `add new row` button.

### This is how I see it

![selection_135](https://cloud.githubusercontent.com/assets/1849174/15660036/a881ea64-26e6-11e6-812e-5fe82893ebed.png)

**Comment by anthonyjb** [comment]
Thanks for the detailed post @a-komarev :+1: 

I do want to provide placeholder text to indicate where to start editing in an empty region and/or text element and I was think along the same lines as we do for table cells where we use the ellipsis (...), e.g:

> ![image](https://cloud.githubusercontent.com/assets/3046287/15739185/c3594992-28a6-11e6-9c31-7eeb0d5bf2de.png)

I want to use the CSS `:empty` pseudo-class to set the placeholder for an empty text element and will allow the placeholder (...) to be overridden by setting a `data-ce-placeholder` attribute (e.g `content: attr(data-ce-placeholder);` in CSS puesdo class).   

I'm opposed to adding a button into the page as a core principal of CT is that the page should as far as possible look identical to the non-editable version of page. But it's a balance and there is a usability issue here, especially with regard to how to add a new paragraph after an image (a question which pops up often). 

Initially before I look to add additional control elements to the page/editor I want to modify the editor so that when an image is selected pressing enter/return should create a new paragraph.

I'm open to further discussion and suggestions on the task at hand.

**Comment by a-komarev** [comment]
@anthonyjb Pressing enter is possible solution, but not intuitive. I think that making feature to add button at the end of each editable region as optional will leave current behavior and will give give more flexibility to your awesome tool.

**Comment by anthonyjb** [comment]
@a-komarev I agree I'm not sure that pressing enter will be obvious to everyone. As I say I'm not keen on the extra button in the the page itself but sounds like I need to take a bit more time to look into a solution for this.

In the next release I'll make sure I add the enter button and placeholder text and leave the issue open for further review. Would appreciate your feedback on this once it's available.

**Comment by a-komarev** [comment]
@andyjbgm sure, I will keep an eye on updates!

**Comment by anthonyjb** [comment]
I've made the changes I described (shortly to be published in release 1.2.7), but I'm not closing the issue at this point as this is just a first step, for the same reason I've moved this issue out of the Release 1.2.7 milestone which will be closed shortly.

**Comment by anthonyjb** [comment]
I've not had any further feedback on this enhancement so I'm closing it for the moment, but happy to re-open if more support for the changes is forthcoming.
