### ISSUE TITLE
Does it work nice with Email?

### ISSUE THREAD

**Issue by katopz** [GetmeUK/ContentTools#23]
Hi guys,

Just curios that anyone use it as email template before?
Does it work well with email client e.g. outlook?

Thanks

**Comment by guillaumepiot** [comment]
@katopz Do you mean as an editor for emails as opposed to web pages?

At the moment, Content Tools focuses on standard HTML pages. In that sense, it is possible to edit an  HTML email template, but the problem comes in with the nature of email HTML, which uses a lot of work-around code to display correctly on multiple platforms (eg: Outlook).

You would need to add extra features such as inlining CSS, and pre-build template with HTML tables which renders well in all email client before hand (here some great examples [internations.github.io/antwort/[(http://internations.github.io/antwort/)). Then, you could create editable regions within that template, where the editor will enable you to change text and images.

**Comment by katopz** [comment]
@guillaumepiot Thanks for input. Antwort look great! I think some workflow like this 

email template -> WYSIWYG custom email content -> finally http://www.sitepoint.com/my-current-html-email-development-workflow/

Would be awesome services email builder/sender (and fun to dev for me)

Cheers!
