### ISSUE TITLE
How do I add new content for editing ?

### ISSUE THREAD

**Issue by alexandrubau** [GetmeUK/ContentTools#24]
How do I add a new title ? Or a new paragraph ? The only option that I see is to edit the existing content.

Thanks.

P.S. - Content Tools looks amazing. Good job !

**Comment by anthonyjb** [comment]
Hi @alexandrubau, You can add new content to any area you've marked up as editable in your template, are you looking at how you might create a new page? Or are you thinking about how you might add a new editable region to a page?

**Comment by alexandrubau** [comment]
Thank you very much @anthonyjb for your help.

I was referring to "If you referring to adding new content within an existing editable area".

I have noticed that holding the shift key doesn't show the pulsating border. I've tried with the left shift, with the right shift, and nothing. I'm using Windows.

Thanks

**Comment by anthonyjb** [comment]
@alexandrubau could you tell me what browser and version you're using?

**Comment by alexandrubau** [comment]
I am using Google Chrome Version 45.0.2454.101 m

**Comment by ahallicks** [comment]
+1 for this, I'm not seeing the pulse for editable regions either in Windows 10 Chrome Version 45.0.2454.101 m

**Comment by anthonyjb** [comment]
The time required to trigger the pulse is set using the ContentTools.HIGHLIGHT_HOLD_DURATION option, it defaults to 2 seconds.

I'm using Version 45.0.2454.85 Ubuntu 14.04 (64-bit) and I don't see and it's working on the demo page of the site. Are you both seeing the issue on the demo page? Can you let me know what OS you're using in case it's an issue with the key events? @ahallicks @alexandrubau

**Comment by anthonyjb** [comment]
So... 

- Version 45.0.2454.99 m on Windows - Not to working.
- Version 45.0.2454.101 m on Windows - Not working.
-  Version 45.0.2454.99 (64-bit) on OSX - Not working.
- Version 45.0.2454.85 Ubuntu 14.04 (64-bit) - Working.
- Version 46.0.2490.42 beta-m (64-bit) on Windows - Working.

**Comment by ahallicks** [comment]
Yeah, Chrome and Firefox don't work for me on Windows 10. However, the function that does the highlighting is being called. I added a console log in the script on my test site and it logged but the classes that do the highlighting don't get added.

**Comment by anthonyjb** [comment]
@ahallicks thanks that's really helpful - I don't have a windows box here but that gives me a starting point to look at.

**Comment by anthonyjb** [comment]
So I finally got a chance to use a few Windows machines today to try to track this bug down, I'd used browserstack to try initially but couldn't reproduce the bug on any version of windows, but today I managed to and after a few console.log statements here's what I found:

Some of the Windows machines (all Windows 8.1 but it's possible this is happening on eaelier/later version too) fire repeated key up/down events when you hold the shift key down, so because there's a time delay that checks to see if the key is being held down the timeout triggering the highlight action is cancelled because of the repeated key up/*down* event - so it never gets called.

It looks like FF has an event property to detect this ([KeyboardEvent.repeat](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/repeat)) but I'm not sure about other browsers yet so I'll experiment a bit more and if I can find a clean solution).

I suspect this may well be occurring on other OSs and browsers.
