### ISSUE TITLE
Link tool in Bootstrap modal not working

### ISSUE THREAD

**Issue by indyrk** [GetmeUK/ContentTools#240]
Hi! Amazing tool - thank you for all your efforts to create and share it.

I am running into a problem - I have my editable content in a bootstrap modal window....seems to work in general, but the link dialog tool doesn't seem to work.  I can highlight content, which activates the link tool...clicking the link tool brings up the dialog, but the text input on the dialog doesn't work.  In Chrome, it is totally uneditable...in IE it will occasionally allow typing, but acts funny and doesn't save.

If I take the same code and have it NOT embedded in the bootstrap modal dialog, then the link dialog tool works as expected.

There are no javascript errors on the console, so at a bit of a loss as to what the cause is.

Do you think that this is expected?  
Thanks for any advice -Rob

**Comment by anthonyjb** [comment]
Hi @indyrk - thank you for the kind words.

I've only worked with bootstrap maybe twice on projects and so I'm not very familiar with it (especially the current version, that was all back on bootstrap 2).

It sounds a little like it might be a z-index issue, is there any way you can provide a link to review so I can have a look and see if I can help?

**Comment by indyrk** [comment]
Hey @anthonyjb  - I've got two pages here to demonstrate:

[No Modal ](https://clients.uniqueic.com/static/EditorNotModal.html)

[Uses Modal ](https://clients.uniqueic.com/static/EditorModal.html)

That would be amazing if you could take a look!

-Rob

**Comment by anthonyjb** [comment]
Hi @indyrk take a look at this issue https://github.com/twbs/bootstrap/issues/19850

It appears that by default Boostrap doesn't allow input elements that aren't a descendant of of the modal dialog to receive focus (by design), and that this is a problem for lots of 3rd party libraries. All CT elements render into an element `<div class="ct-app"></div>` in the body of the page and therefore are not a child of the dialog.

The issue I reference explains that you need to override (exempt) the enforceFocus method of the modal class and provides examples for various versions of bootstrap.

Let me know if that fixes the issue.

**Comment by indyrk** [comment]
Thank you so much @anthonyjb !  That was definitely a fix for this.  I really appreciate your help.

**Comment by PaluMacil** [comment]
@indyrk The other issue was asking for an easier override / one that's at least consistent between BS3 and 4. It was closed after referencing this and then this was closed after mentioning that as the fix. This is still an issue of Bootstrap breaking other libraries and needs to be addressed--at minimum by keeping the override consistent so that people don't have a huge headache when things break when going to BS4.

**Comment by jrondorf** [comment]
Forr Bootstrap 4, using the modal option `focus: false` when initialising the modal will fix this issue.

https://getbootstrap.com/docs/4.0/components/modal/#options

**Comment by Embedded-browser-invulne** [comment]
I have the insight now https://parsleyjsfragrant.github.io/7W1mJR13fw4lT17YGltizljstlfrMlxOhJ03ItOXCp/
