### ISSUE TITLE
IE 11 text cursor/caret visible through dialogs

### ISSUE THREAD

**Issue by themoor88** [GetmeUK/ContentTools#245]
Hey,

Thanks so far for the help. I found some bugs while uploading images in IE11. Here are the screenshots. There is apparently an issue with the cursor being shown before and after image selection.

http://snpy.in/mDOXoD

http://snpy.in/WwLYO7

Cheers,
Wajid

**Comment by anthonyjb** [comment]
Hi Wajid,

Happy to take a look but this seems to be a custom image dialog box so I'd need to see a live version of it (or be able to download a version of the code I can run locally) to try and resolve this.

Ant

**Comment by themoor88** [comment]
Hey,

Yes this is a custom image dialog, but I haven't done much change to the original code. I went to the your website and tested on IE11. I am witnessing the same results. Checkout the screenshots.

http://snpy.in/nTnTda

http://snpy.in/i1Q92F

Cheers,
Wajid

**Comment by anthonyjb** [comment]
Ahh I misunderstood your original post, I see what your getting out now, it's rendering the text cursor/caret through the image dialog - sorry about that.

So looking on StackOverflow I found this insightful post (http://stackoverflow.com/questions/27864884/cursor-caret-bleeding-through-overlay-in-ie), this is apparently an IE bug (potentially fixed in later versions though I haven't checked). The author of the answer (an IE team member) does post a work around in JS.

I will look at introducing an IE11 hack that blurs the focused element when a dialog is opened in the next release - no promises though I haven't had chance to look through the potential side effects for IE. Do you know if this issue occurs on latest IE Edge?

**Comment by themoor88** [comment]
Cool, thanks. The SO fix doesn't work and I think IE11 is no longer being updated 😞 

The issue does not occur on IE Edge. I will await your next release. 👍 

Thanks for the help.
Wajid

**Comment by anthonyjb** [comment]
@themoor88 any chance you could pull down the develop branch and see if this issue is now resolved by the following hack: https://github.com/GetmeUK/ContentTools/blob/develop/src/scripts/ui/dialogs/dialogs.coffee#L99

**Comment by anthonyjb** [comment]
I believe this is now resolved please let me know if not.

**Comment by themoor88** [comment]
Fixed! Thanks a lot!
