### ISSUE TITLE
How to send hidden inputs value  in every request

### ISSUE THREAD

**Issue by aniket27** [GetmeUK/ContentTools#247]
To know which user is posting content & getting all other info how can i send hidden inputs value with every ajax request

**Comment by anthonyjb** [comment]
Hi @aniket27,

For determining which user has made changes to the content I would recommend using cookies to store session information about the current user.

In terms of sending other information through when saving your changes via AJAX, it depends a bit on your framework (e.g JQuery, MooTools, etc.) but using vanilla JS you can just do:

```JavaScript

// Create a payload object
var payload = new FormData();
payload.append('nameOfHiddenField', 'valueOfHiddenField');

var xhr = new XMLHttpRequest();
xhr.open('POST', '/save-my-page');
xhr.send(payload);
```

If you look at the [Save changes](http://getcontenttools.com/getting-started#save-changes) section of the *Getting started* guide you should see how this fits in.

---

On a slightly different note, I hope this doesn't come off as rude, but I'm trying to get people to post questions, issues, suggestions and so on in the right place. On the readme is a short guide for deciding where to post you items:

- How do I? -- StackOverflow
- I got this error, why? -- StackOverflow
- I got this error and I'm sure it's a bug -- post an issue
- I have an idea/request -- post an issue
- Why do you? -- chat with me on gitter (I may then post it as an issue)
- When will you? -- chat with me on gitter (I may then post it as an issue)
- You suck and I hate you -- contact us privately at pm@piersmorgan.me!
- You're awesome -- please find a megaphone and suitably high rooftop (but seriously any help spreading the word about ContentTools is much appreciated)

Neither of these questions are directly related to ContentTools and the questions would be better posted on StackOverflow as there's a large volume of people who can help there and once an answer is posted there people are more likely to find it in future rather than ask it again.

I check StackOverflow daily so as long as you mention ContentTools in your question I should find posts and I always try to answer where I can promptly.

**Comment by aniket27** [comment]
How could i achieve it via jquery?

**Comment by anthonyjb** [comment]
JQuery allows you to send a `data` object to the AJAX call:

```JavaScript

var data = {};

// Add hidden fields
data['nameOfHiddenField'] = 'valueOfHiddenField';

// Add regions
for (name in regions) {
    if (regions.hasOwnProperty(name)) {
        data[name] = regions[name];
    }
}

$.ajax({
    method: "POST",
    url: "...",
    data: data
}).done(function( msg ) {
   ...
});
```

Hopefully that helps you - but to clarify I haven't used JQuery in nearly 2 years so I'm certainly not an expert on how best to make an AJAX call with JQuery, StackOverflow is the best place for this kind of question.

**Comment by aniket27** [comment]
Thanks alot for your fast reply. Just some hours ago i opene up my page in mobile browser & i found when i click on insert image the popup is not responsive, is there a way to make the popup responsive

**Comment by anthonyjb** [comment]
Hi @aniket27 - CT does not currently support mobile / touch based devices for editing content. I do hope to add support for mobile at some point in the future once the library becomes more mature.
