### ISSUE TITLE
Dynamically update content [question]

### ISSUE THREAD

**Issue by brunjick** [GetmeUK/ContentTools#253]
Hello, I've searched a lot but couldn't find a way to dynamically update content (previously saved html).
What I've found, that may be related to what I want, is these two methods `editor.syncRegions(regionQuery)` `stack.replaceRegions(regions)`, but can't do anything with it, documentation is so unclear to me.

**Comment by anthonyjb** [comment]
Hi @brunjick, can you describe what you're trying to do sorry? When you say 

> dynamically update content (previously saved HTML).

- Are you adding content into the editable regions?
- Is the editor active (e.g editing) when you're making the change?

`syncRegions` (which will work if the editor is editing or not) looks for new or removed editable regions since `syncRegions` (which is also called by `init` and `start`) was last called. What it wont cater for is the contents of a region being modified while the editor is active, it doesn't re-parse regions it already knows about.

I agree the documentation on this function isn't documented as well as it needs to be be and will flag this as an enhancement, will get a better example up in the next release.

**Comment by brunjick** [comment]
@anthonyjb Thanks for quick response. I'll try to explain in detail.
In my project, users have ability to write and edit posts, so I've editor with one region for writing post, and I'm doing autosave every one second, which works well. But I also have list of posts in sidebar, to let users quickly switch between them. My application is SPA, so I don't want to refresh page when user clicks on another post to edit. So, have can I replace content in editable area with new data, that I fetch dynamically? I don't even know from where to start with. Should I manually update DOM and call `syncRegions`?

**Comment by brunjick** [comment]
PS. I was previously using medium editor, and what I want was easily implemented there, you can take a look at `setContent` function for reference https://github.com/yabwe/medium-editor#helper-methods

**Comment by anthonyjb** [comment]
OK I think I get it :) I'm guessing that posts each have a unique ID and that at any one time there's only one editable region (e.g you can only edit one post at a time). 

If you don't want to stop/start the editor when switching to a different post then my advice would be to do the following:

**Replacing the region**

- Use the post ID in the region name to ensure it will be unique, for example `<div class="post" data-editable data-name="post-123">`
- When you switch between posts, remove the current editable region and replace it with a new region for the switched to post and ID, so now the editable region might be `<div class="post" data-editable data-name="post-124">`
- Call `syncRegions` against the editor which should then recognize the new region and forget the old one.

**Comment by anthonyjb** [comment]
I'm happy to look to add a `setContent` method to editable regions (sounds like a good idea). Would you mind making the request against the issue tracker here: https://github.com/GetmeUK/ContentEdit/issues (as the change would be against that library).

**Comment by brunjick** [comment]
@anthonyjb Thank you very much, I made it.

**Comment by anthonyjb** [comment]
@brunjick OK the `setContent` is now a method against the `Region` class and I've updated the documentation for `syncRegions` along the lines of our conversation.
