### ISSUE TITLE
add a class 'viewImg' to an image

### ISSUE THREAD

**Issue by FrancoisYu** [GetmeUK/ContentTools#286]
The following is the code I'm using for adding a class to each image I've insert in the CT, but it seemst that doesn't work:

```
 ContentEdit.Root.get().bind('attach', function(element) {
        if (element.type() == 'Image') {
            ContentEdit.addCSSClass(element._domElement, 'viewImg');
        }

        return ContentEdit.addCSSClass(element._domElement, 'js-question');
    });
```

Is there any way I can do that?

**Comment by anthonyjb** [comment]
@FrancoisYu you must add the class to the element not the `_domElement` (which technically would be better accessed as `element.domElement()`). Like so:

```
element.addCSSClass('viewImg')'
```

If you don't the class only exists against the DOM element which will be unmounted/mounted at somepoint and the class will be lost. So I suppose if you only wanted the class to appear in during editing you could change this to the `mount` event instead of the attach event.

I saw you mentioned in  a previous post that `element.addCSSClass` this wasn't working for you - if this is the case please provide an otherwise working example where I can test this behaviour.

**Comment by FrancoisYu** [comment]
The reason I'm using element._domElement is that I've got an error msg if I use the .element, I think it's related to the meteor framework. The following is the debug screen shot I took from the Chrome. Is there anything I can do to use ContentEditor.addCSSClass('element', 'viewImg')
![a getattribute_is_not_a_function](https://cloud.githubusercontent.com/assets/10751834/17795469/316961e8-65eb-11e6-9bff-da6d7edb3873.png)

**Comment by anthonyjb** [comment]
Hi @FrancoisYu,

OK not sure if your comment here means you've now resolved your issue with meteor (https://github.com/GetmeUK/ContentTools/issues/283#issuecomment-240908357), but regardless the reason you can't use `ContentEdit.addCSSClass(element, 'viewImg');` is because that function expects a DOM element not an CE Element (which doesn't have a `getAttribute` method hence the error). So you need to call `element.addCSSClass('viewImg')` to add a class to the image Element. 

I'm not sure why attach isn't being called with the image, again ideally step is to figure out if you get this problem trying to bind to the event in the sandbox demo, if not then we need to look at set up specifically for meteor.

**Comment by FrancoisYu** [comment]
Yes, I've solved the problem by using the code :  

`element.addCSSClass('viewImg');   //working`

I will try to use the sandbox demo, but since I'm using the Meteor, I may have to re-code the .js to fit the Meteor style.

Thanks again for you kindly help. I do really enjoy using your CT in my project.
