### ISSUE TITLE
DOM elements (specifically table) deleted/re-organized on clicking "edit"/"save" buttons

### ISSUE THREAD

**Issue by danielleford04** [GetmeUK/ContentTools#287]
I'm using an email template in the content editor and when I press "edit" or "save" content is being moved from the table its in to a new table (without the important classes), or table rows are being combined (changing the layout styles)

Notice that originally, the left column image and p were in the same row. After pressing the edit button, each image and paragraph becomes its own table row. How do we get around this? I tried adding unique classes to each tr, which succeeded in preserving those two rows, but other things started disappearing/being combined instead.

Here's the code (and screenshots) of the first instance of the issue. 
original code: ![origcolumn](https://cloud.githubusercontent.com/assets/13168696/17816325/e19810d2-65f5-11e6-8b8a-49fb6f2bac57.png)
html after pressing "edit": ![screen shot 2016-08-19 at 10 14 06 am](https://cloud.githubusercontent.com/assets/13168696/17816328/e5a5cd72-65f5-11e6-86cd-664e6d78d7a1.png)
what it looks like originally: ![screen shot 2016-08-19 at 10 14 45 am](https://cloud.githubusercontent.com/assets/13168696/17816331/e8683af4-65f5-11e6-8271-e8e3bc126e40.png)
what it looks like after pressing "edit": ![screen shot 2016-08-19 at 10 14 54 am](https://cloud.githubusercontent.com/assets/13168696/17816334/ea50a770-65f5-11e6-8428-5b3cc2d25661.png)

Thanks,
Danielle

**Comment by anthonyjb** [comment]
Hi @danielleford04,

I'm not sure of the precise cause of this behaviour however the editable `<td>` elements in ContentEdit are only designed to take inline HTML not block level elements (see the intro and limitations section to HTMLString here http://getcontenttools.com/api/html-string) and I suspect this may well be playing a part in the problems your seeing.

It would be really useful if you could provide the actual HTML here so I can have a go at reproducing the issue myself.

One possible option you might try here also (since from your HTML screenshots it appears you need the the contents of the `<td>`s themselves to be editable, would be to make `<td>`s containing editable content regions themselves instead of the entire block, e.g:

```HTML
<table>
    <tr>
        <td data-editable="region-name">
            <h3>Title</h3>
            <p>Body</p>
        </td>
        ...
    </tr>
</table>
```

If you can provide the HTML in a format I can copy and paste into a text file I'd appreciate that as I'd like to investigate this behaviour further.

**Comment by danielleford04** [comment]
Hi @anthonyjb -

I'll look more into that, thank you for the link. I've included the jade for the whole editable area (most of this is what's -inside- of the area but i included the editable region). It is, however, jade and not html! If you want more of the code, let me know...
[editable.txt](https://github.com/GetmeUK/ContentTools/files/429168/editable.txt)
(I really hope this file format preserves formatting)

**Comment by anthonyjb** [comment]
Hi @danielleford04, hanks for the file if you could also post the output HTML that CT runs against that would be awesome (sorry I should have been more specific initially).

Do let me know how you get on and if the alternative approach works out for you.

**Comment by danielleford04** [comment]
Ah! I copied and pasted code from Dev Tools and unfortunately formatting was not preserved...but here is the code before and after the save

[code.zip](https://github.com/GetmeUK/ContentTools/files/431247/code.zip)

**Comment by danielleford04** [comment]
The alternative approach works! Though it will also require an alternative saving approach. Thanks!
