### ISSUE TITLE
Is there a select all function?

### ISSUE THREAD

**Issue by Hoiy** [GetmeUK/ContentTools#297]
Is it possible to select all text and paragraphs for copying and pasting the full article in other editor?

**Comment by anthonyjb** [comment]
Hi @Hoiy,

You can't select more than one block of content (e.g a paragraph, list item, table cell) to copy while in edit mode. 

If you want to copy to another editor (non CT editor) then you may be able to copy the page content while in non-edit mode (just using the standard Copy & Paste). If you want to copy into another page that's also using the CT editor then at the moment that wont work, well at least you'll lose all formatting. Adding support for HTML copy & paste is a planned enhancement https://github.com/GetmeUK/ContentTools/issues/115

Sorry I don't have better news for you right now - I'm currently working on some CE edits to add support for tab indenting for `pre` blocks, HTML C&P is a feature we want for our clients soon though so it's high on my list.

**Comment by Hoiy** [comment]
@anthonyjb Thanks for your shift response! Good to know that it is a planned enhancement.

**Comment by slowfattler** [comment]
Hey! 
First of all I am very thankful for the Content Tools! I find them rather terrific. There is ONE Issue though thats bugging me a lot:

I have a situation, where it would improve workflow A LOT if i could select and manipulate Text across paragraphs... 

I have to transfer couple hundreds of formatted Dokuments from Word to a online Plattform. 
Since Authors heavily used paragraphs in their Dokuments, when copy paste them into CT i am left with sooo many single blocks which i cannot edit properly. 

one big issue are lists: when paste a list from office, each line becomes a separate paragraph which won't transform into a list (as there are no more line in this paragraph) 

Changing the breaks in the text to inline breaks (shift+enter) does not help either. 
Do you know any hack i could use maybe to ship around this issue?

any help appreciated!

Thanks

**Comment by koutsenko** [comment]
How can i programmatically select all region.children[0] content? I already make it focused, so i want to delete old content while started typing new.
