### ISSUE TITLE
Using .bind() and .unbind()

### ISSUE THREAD

**Issue by l2aelba** [GetmeUK/ContentTools#305]
I will **detect** if contents are **modified**, so add something...

``` javascript
ContentEdit.Root.get().bind('taint', function (element) {
	if(element._cached) {
		element._parent._domElement.setAttribute('data-edited','');
	}
});
```

But when done so **unbind** it like this : _for better performancer_

``` javascript
ContentEdit.Root.get().bind('taint', function _func(element) {
	if(element._cached) {
		element._parent._domElement.setAttribute('data-edited','');
		ContentEdit.Root.get().unbind('taint', _func);
	}
});
```

**Problem is** this only work with **one region**, Any idea how to **bind** and **unbind** taint _(when done)_ for **every regions** ? _(with good performance)_

Thanks so long

**Comment by anthonyjb** [comment]
Hi @l2aelba - I'm struggling a little to work out what's going on here, I'm unsure why you are you testing for `_cached`? What are you checking here?

However the reason this isn't working has nothing to do with regions it's because as soon as you get a `taint` event against `root` you then `unbind` the listener. So no more `taint` events against root are sent to you listener (which makes it appear as if it only works for one region, in reality this means it only works for one `taint` event).

Performance wise I doubt you need to worry about a function being called every time an element is `taint`ed instead you might try simply making sure you don't call the `setAttribute` attribute each time:

```JavaScript
ContentEdit.Root.get().bind('taint', function (element) {
    if(element._cached && !element._editedSet) {
        element._editedSet = true;
        element._parent._domElement.setAttribute('data-edited','');
    }
});
```

**Comment by l2aelba** [comment]
@anthonyjb Thanks for this. (Sorry for late answer)

That I want to trigger is about if domRegion(s) has been edited.

Example :
- User write down something <-- Edited
- User undo (cmd+z) until to the default <-- Not edited
