### ISSUE TITLE
Q: triggering events on start / stop

### ISSUE THREAD

**Issue by Paulloz** [GetmeUK/ContentTools#31]
Hi there.
I think it'd be cool to have the editor trigger events on `start` and `stop`.
I can make a PR for that but would like to discuss beforehand if there's any reason not to do that.

**Comment by anthonyjb** [comment]
I've considered adding support for this numerous times and I'm in favour. Things that have stopped me from doing so so far are:

- Where the event should trigger? As in at the start/end of the method, this could be solved with `onstart`, `afterstart` style events but that wouldn't be consistent with existing event names.
- The event system is very basic, you can't prevent the default action triggering the event for example (e.g no `preventDefault` or equivalent). This often means that you have to revert to monkey patching the start/stop methods (as in some of the examples I've posted) when you want to modify behaviour.

However monkey patching is not ideal it makes it difficult to decouple code for one so I welcome your  thoughts on this.

**Comment by Paulloz** [comment]
Well, I didn't dig the event system at all and don't know where you'd like to go with this.
A very pragmatic thought however: your second note seems relevent only if the event is fired at the start of the method.
Imho it depends on how this event system is used. Is it only noticing other elements of one's state? Is it to prevent stuff from happening in certain situations?  
I must admit I have not thought of anything before filing this issue and that this open some questions.

**Comment by anthonyjb** [comment]
One question it raises is the suitability of such a basic events system for a UI, the approach for ContentTools came from ContentEdit where events are really just simple notifications to a Root node. But here in ContentTools events are being used to manage individual UI components and perhaps a more complete event system that allows behaviour to be modified is required.

**Comment by bfintal** [comment]
For my own use, I also need a start event so that I can attach another mousedown event to different toolUIs in the toolbox.

**Comment by bfintal** [comment]
One solution I can see is to mimic the set up of the existing `save` event - where the last line of the function is an event trigger.

Submitted PR #40

**Comment by anthonyjb** [comment]
Hi @bfintal so what you've suggested is what I'd recommend as a short term resolution for individual projects (nothing wrong with your CoffeeScript btw :+1:), you could either update the editor directly as you've done or you could monkey patch the methods if you'd prefer to keep the code separate, e.g:

    var editorCls = ContentTools.EditorApp.getCls();
    editor.start = function () {
        editorCls.prototype.start.call(this);
        editor.trigger('start');
    }

    editor.stop = function () {
        editorCls.prototype.stop.call(this);
        @trigger('stop');
    }

But this solution doesn't provide enough control for many scenarios because:

- The event is triggered after the action has happened, sometimes you might want to trigger before hand.
- There's no way to prevent the default action using the triggered event (e.g ev.preventDefault())
- You don't know if stop was called because the user saved or cancelled (this could be resolved easily though by adding a cancelled event or by updating the editor to pass this flag).

Ideally the event system would allow a function to:
- Be bound to before or after an event is triggered.
- Allow the function to determine whether the default behaviour executes.
- Allow the function to determine whether other bound functions after this one are executed.

I have an event system on an early prototype of this library that supports all of this but it felt heavy and when I was re-factoring so I stuck with a much simpler notification system but I think it's too simple for a UI.

I think now that there's at least 3 of us (including myself) who have all determined there should be a more extensive set of events and that additional functionality is required than currently provided it's clear we're going to need to add this to the to do list.

**Comment by bfintal** [comment]
@anthonyjb Yes that would be ideal. If there's something like that then I would be able to also attach handlers to the toolbar buttons, this was one of the intentions for the need for a start event.

I would be able to fix this quite hacky code :)

	window.GBEditor.getToolUI = function( name ) {
		return ContentTools.EditorApp.get()._toolbox._toolUIs[ name ];
	};
	
	var tool = window.GBEditor.getToolUI('align-right')._domElement;
	tool.addEventListener('mousedown', function() {
		console.log('clicked');
	});

I'm all against keeping my own separate codebase, I'd rather send a PR :)

**Comment by frankbardon** [comment]
Since some of the other areas of development seem well in hand, I'll volunteer to extend the even system. My only question would be: If you plan on moving to NPM, there are excellent event handling libraries out there, and no need to re-invent the wheel. Perhaps this is part of that process, since there will be significant changes to the codebase at the same time?

**Comment by anthonyjb** [comment]
Sightly of topic but... 

I'll hold my hands up and say part of the reason I haven't made much progress on publishing via NPM is I just don't know enough about the process and haven't had time to look into it in detail. I read through some basic tutorials and from what I read I wasn't aware there would need to be a major shift in the code base to move to NPM but would appreciate any guidance you can give me in this area particular what changes will be required.

Updating the event system is a big undertaking so any help would be very much appreciated, the current event system is simple and lightweight but just doesn't cut it for a UI and patching is problematic especially when you want to change behaviour of key methods in different sections of the code (e.g can't patch the `start` method twice).

The biggest stumbling block with the existing system is there's no way to change the flow, you can't prevent a default action from occurring and whilst technically it would be possible to do this by triggering events before and after the code you execute and then perhaps checking the return value this would be very ugly in the code, e.g:

```
method: () ->
    if not @trigger(''onmethod')
        return
    
    ...some default action...

    @trigger('aftermethod')
```

I was wondering if it might be possible to simply use the DOM event system since it's there (no overhead and requires no dependencies), well known and documented?

**Comment by anthonyjb** [comment]
@frankbardon sorry for the slightly delayed responses to your last couple of comments - your picking some of the bigger tasks to tackle and they take a while to mull over in my head :)

**Comment by Cyrille37** [comment]
Hi,
I use a dirty fashion to get fired on start/stop events : 
```
    var editor = ContentTools.EditorApp.get();
    var ignition = editor._ignition ;
    ignition.bind('start', function() {
      console.log('Start editing !');
    });
    ignition.bind('stop', function() {
      console.log('Stop editing !');
    });
```
Is there some news about this enhancement ?
Cheers.

**Comment by gabipetrovay** [comment]
If an event refactoring is going to happen, it would be nice to have some events to catch when working with the UI (opening and closing dialogs). Also extending the UI (a new dialog, a new toolbox, or extending a toolbox with more actions) should be easy to write as plugin code.

**Comment by anthonyjb** [comment]
Release 1.2.0 now supports for start/stop events against the editor (http://getcontenttools.com/api/content-tools#editor-app). 

Events now supports cancelling of the default action by calling `preventDefault()` and halting the execution of subsequent callbacks by calling `stopImmediatePropagation` (http://getcontenttools.com/api/content-tools#event). 

With the new model in place I'm now comfortable adding additional events when required for the UI.
