### ISSUE TITLE
Dialogs and body scrollbar

### ISSUE THREAD

**Issue by cadilhac** [GetmeUK/ContentTools#310]
While still in discovery mode of your library, I noticed that when I trigger the image upload dialog or the video dialog, it appears well with a grey overlay, but the vertical scrollbar of my page disappears, creating a slight shift of the page content. It reappears when the dialog is closed.

**Comment by anthonyjb** [comment]
@cadilhac I believe what you describing is because we fix the height of the page to prevent the content in the background being scrolled while a dialog is open (e.g setting the height of the body to no greater than the height of the window removes the scroll bar and the content shifts slightly), therefore this  behaviour is intentional.

**Comment by anthonyjb** [comment]
@cadilhac if you wanted to change this behaviour btw you can by overriding the CSS modifier class `.ct--no-scroll` (https://github.com/GetmeUK/ContentTools/blob/master/src/styles/content-tools.scss#L61)

**Comment by cadilhac** [comment]
Hummm... jsut wondering how it could scroll if you display an overlay covering the whole surface. I designed an angular component with a sliding panel and a full size overlay and I don't get any scrolling of the page behind...

**Comment by cadilhac** [comment]
oh I remember what I'm doing in my library. Like you I set hidden to the body overflow, but I also add a margin-right equal to the size of a scrollbar. This does the trick to cancel the shift.

**Comment by anthonyjb** [comment]
I'm not familiar with Angular UI components but and how they bahave but just placing an overlay over the whole screen doesn't prevent the page contents from scrolling in plain HTML/CSS. 

The reason I disable it is so that should I have scrollable content within my overlaid UI component (such as the list of attributes or code window within properties dialog) there want be 2 scrollable regions on the page (especially over each other).

I'd have to use JS to add margin to match the scrollbar because there might not be a scrollbar and I believe (I could be wrong) that there's no way to specify the size of the scrollbar in CSS safely and future proof - you'd need to measure this. Whilst this might be a nice feature if someone wishes to contribute it it isn't something I consider a bug/issue.
