### ISSUE TITLE
Image scale is incorrect for large image if it is loaded directly

### ISSUE THREAD

**Issue by Hoiy** [GetmeUK/ContentTools#313]
1. Visit demo page http://getcontenttools.com/demo
2. Insert an image tag to editable content in preview mode, for example `<img src="http://jeffpicard.com/blog/wp-content/gallery/widescreen-wallpaper-full-size/yellowleaves.jpg">`, this image has size 1900x1200.
3. Enter edit mode and then exit edit mode, it is found that width="1900" and height="488" is added to the output img tag.
4. Furthermore, if you try to resize the image in edit mode, part of the image is trimmed.

![screen shot 2016-09-20 at 7 30 13 pm](https://cloud.githubusercontent.com/assets/4758788/18668555/b99b650c-7f68-11e6-8063-22a3ab69619f.png)

**Comment by anthonyjb** [comment]
Hi @Hoiy, I believe this is simply the CSS on the demo website which limits images to 780px in width, it's not a limitation of ContentTools but the design I put in place.

**Comment by Hoiy** [comment]
@anthonyjb I am not sure if it is a correct behaviour for an input img tag `<img src="http://jeffpicard.com/blog/wp-content/gallery/widescreen-wallpaper-full-size/yellowleaves.jpg">` (of size 1920x1200) to become `<img width="1920" height="488" src="http://jeffpicard.com/blog/wp-content/gallery/widescreen-wallpaper-full-size/yellowleaves.jpg">` after changing to edit mode and then back to preview mode.

Moreover, the user really has no chance to see the original picture once they resized it in edit mode, only the trimmed one.

**Comment by anthonyjb** [comment]
Hi @Hoiy,

**Width and Height attributes**
We store the width and height of the image as attributes when the image is made editable so that we can determine the aspect ratio (which is used when resizing the image), if no width/height attributes are set against the image when we make it editable we extract them from the image itself using `natural/clientWidth/Height`.

We set the width and height as attributes against the image on `html` output by default because;

- this is good HTML practise (I believe) as it helps in the initial page render by indicating how much space needs to be reserved for said image (less content jumping), 
- and it's often useful in allowing devs to review the HTML on save for changes in image sizes that once identified are enacted as changes to the physical image, e.g for us:
    - we review the HTML
    - find images that have changed in size
    - generate new versions of those images at their new sizes
    - update the image src within the HTML to point to the newly resized images 
We don't change the image on the fly purely for efficiency and simply rely on the browser scaling the image until the page changes are saved.

I'm not saying it's the correct behaviour, or even the best solution in all cases, but for our set up it works well and hence has become the default behaviour.

Having said that if this behaviour is causing an issue for your project it is possible to change it, either by patching the `html` method for image elements to exclude the width/height attributes on output or you could also patch the `fromDOMElement` method to flag whether or not the width/height was set or extracted and then have the `html` only output a new width/height attribute if one was originally set. If you need to do this let me know and I can provide an example of how.

**Trimming**
I'm not really sure what you mean by trimming the image, as per my previous comment the trimming you've highlighted in your image on the demo page only occurs because that's how the CSS is set up, it's to do with CSS nothing to do with CT.
