### ISSUE TITLE
Preserve Line-Breaks On Save?

### ISSUE THREAD

**Issue by haberman13** [GetmeUK/ContentTools#319]
Anyone know how to preserve a line break when the editor.stop() method is called?

The line breaks will be kept if there is text below them.

E.g.

"some text < br > more text" - line break remains
"some text < br > < br >" - line breaks removed

**Comment by anthonyjb** [comment]
Hi @bcreeves this is by design though it's been debated back and forth - there is a patch/workaround if you want to change this behaviour but it isn't pretty, please see this issue for further information: #113 

There is an also open issue (https://github.com/GetmeUK/ContentEdit/issues/10) for adding a setting to allow this behaviour to be configured in ContentEdit.
