### ISSUE TITLE
Move toolbox with translate() instead of using absolute coordinates

### ISSUE THREAD

**Issue by boyum** [GetmeUK/ContentTools#328]
This appears not to be too big of a performance issue, but the toolbox should be moved with CSS transformations, and let the GPU do the translation, instead of using absolute coordinates (`left: ... px;top: ...px`).

**Comment by anthonyjb** [comment]
Hi @Boyum,

I think this is probably a good approach to take for positioning of elements of this nature and I'd be happy to accept a pull request if you'd like to implement the change (or indeed to look at making the change myself moving forward).

I say probably because whilst I don't believe there are any issues with applying the translate approach to the toolbox or other elements you don't know until you try :) 

Another thing to consider, the only article I can find online with benchmarks (from an admittedly rather quick google search) is this one from 2013 https://blog.tumult.com/2013/02/28/transform-translate-vs-top-left/ and my interpretation of the benchmark charts here seem to show a rather mixed set of results where translate doesn't always win over position, if anyone knows of a more up to date set of benchmarks that would be really interesting.

Thanks for the suggestion, Ant :)

**Comment by anthonyjb** [comment]
I'm closing this as I can't see it being at the top of my list ever, I'm still not sure there's any real benefit to it and no one has submitted a PR for it in some time.
