### ISSUE TITLE
Using ContentTools with iframes

### ISSUE THREAD

**Issue by Petah** [GetmeUK/ContentTools#348]
I am trying to get ContentTools to work using iframes (same origin). Basically what Im wanting is to initialise ContentTools in the `top window`, but have the editable regions inside an iframe.

It seems to somewhat work (yay!), but there is a couple of strange issues. Like for one when pressing enter the new `Text` elements are added above rather than below. 

Is this something you would consider supporting, potentially if I work on some pull requests to fix some of the issues?

I threw a quick example in here: https://github.com/Petah/ContentTools/tree/test/iframe/sandbox

**Comment by anthonyjb** [comment]
The issue is to do with ContentSelect using the window it is initialized in to select the current selection range from, there are a couple of related issues on the topic that might be of interest:

- https://github.com/GetmeUK/ContentTools/issues/284
- https://github.com/GetmeUK/ContentEdit/issues/14

A possible quick patch would be to patch the ContentTools replacing `window.getSelection()` with `(iframe.contentWindow || iframe.contentDocument.defaultView).getSelection()` where `iframe` is a reference to your iframe.

Longer term as this is the third request regarding this issue (or similar) I think it might be worth posting a feature request for the ContentSelect library to allow a target window to be set.
