### ISSUE TITLE
How do you cancel saving the right way?

### ISSUE THREAD

**Issue by DeveloperInResidence** [GetmeUK/ContentTools#350]
I need to validate a form field when you try to save content in the editor, but am having trouble figuring out how to do it a way that works.
I've tried the following, but one editable part remains as editable if you first cancel the save, correct the problem and save:
```
editor.addEventListener('stop', function (ev) {
	$name = $("#html_name"); // The form field
	if($name.val().trim() == "") { // The field is empty
                // Show error message
		$name.focus();
		ev.preventDefault(); // Prevent save
		ev.stopImmediatePropagation(); // Prevent save
		editor.ignition().edit(); // Don't hide the save/revert buttons
	}
});
```
How do I cancel saving/reverting the editor the right way?

**Comment by anthonyjb** [comment]
Hi @DeveloperInResidence,

I suspect this might be because you are triggering start against the editor twice by calling edit against the ignition. Instead of calling edit to keep the ignition's state in editing mode I'd recommend you set the state e.g:

```JavaScript
editor.ignition().state('editing');
```

This will prevent a the event bound to the ignition for edit being triggered.

**Comment by DeveloperInResidence** [comment]
Thank you, that worked right away!
