### ISSUE TITLE
element.isFixed is not a function

### ISSUE THREAD

**Issue by Teddy95** [GetmeUK/ContentTools#360]
I've got this error message:
![screenshot_1](https://cloud.githubusercontent.com/assets/3901133/20965845/e6cb6e90-bc77-11e6-9383-37d9079a5809.png)

I have used the sample code from the tutorial and it has worked. But tomorrow it don't, without changing the source.

content-tools.min.js contains the code from content-tools.js

**Comment by anthonyjb** [comment]
Hi @Teddy95,

This looks like it might be a bug since there's no reason an element at that point shouldn't have that function, for reference I believe it's falling over here in the code: https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/ui/inspector.coffee#L154

Could you help me by providing:

- The browser version this error occurred in
- Ideally the JS and HTML your using
- Steps to reproduce the error

Thank you in advance

**Comment by Teddy95** [comment]
Hi @anthonyjb,

Mozilla Firefox 50.0.2

I use the default contenttools js and css files and additional the file editor.js with following content.
```javascript
(function () {
	window.onload = function () {
		ContentTools.StylePalette.add([
			new ContentTools.Style('Alert info', 'alert alert-info', ['p']),
			new ContentTools.Style('Alert success', 'alert alert-success', ['p'])
		]);

		ContentTools.DEFAULT_VIDEO_WIDTH = '800';
		ContentTools.DEFAULT_VIDEO_HEIGHT = '450';
		ContentTools.INSPECTOR_IGNORED_ELEMENTS = ['pt_module_include'];

		editor = ContentTools.EditorApp.get();
		editor.init('*[data-editable]', 'data-name');

		window.addEventListener('load', function() {
			var editor;
		});

		editor.addEventListener('saved', function (ev) {
			var name, payload, regions, xhr;

			// Check that something changed
			regions = ev.detail().regions;

			if (Object.keys(regions).length == 0) {
				return;
			}

			// Set the editor as busy while we save our changes
			this.busy(true);

			// Collect the contents of each region into a FormData instance
			payload = new FormData();

			for (name in regions) {
				if (regions.hasOwnProperty(name)) {
					payload.append(name, regions[name]);
				}
			}

			// Send the update content to the server to be saved
			function onStateChange(ev) {
				// Check if the request is finished
				if (ev.target.readyState == 4) {
					editor.busy(false);

					if (ev.target.status == '200') {
						// Save was successful, notify the user with a flash
						new ContentTools.FlashUI('ok');
					} else {
						// Save failed, notify the user with a flash
						new ContentTools.FlashUI('no');
					}
				}
			};

			xhr = new XMLHttpRequest();
			xhr.addEventListener('readystatechange', onStateChange);
			xhr.open('POST', document.getElementById('ajaxUrl').value);
			xhr.send(payload);
		});
	};
}).call(this);

```
The editor is used in a content management system (my own), so I can't unfortunately provide the whole code to reproduce the error.

**Comment by Teddy95** [comment]
I have delete `ContentTools.INSPECTOR_IGNORED_ELEMENTS = ['pt_module_include'];` from source, now it's working.

**Comment by anthonyjb** [comment]
@Teddy95 thanks for the extra information. So I don't think you need to add pt_module_include to the list of `INSPECTOR_IGNORED_ELEMENTS` based on the code you've presented, this list is only for `ContentEdit` elements, so unless you have created a custom `ContentEdit.Element` class that returns `pt_module_include` when calling `type()` this isn't required.

What causes the issue is that you are redefining the list of elements rather than adding to it and so elements that should be ignored (like `Region` in this case) are not ignored and since they don't support the `isFixed` method they fall over. The list of inspector ignored elements is defined in the namespace file here: https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/namespace.coffee#L56

If you wanted to add another element class to this list you'd typically approach by redefining the whole list or using `push` to add the element type to the existing list, e.g: `ContentTools.INSPECTOR_IGNORED_ELEMENTS.push('pt_module_include')`

On this basis I don't consider this a bug but I'm grateful that you came back to me with the additional info as it save me quite a bit of time investigating :+1:

**Comment by Teddy95** [comment]
Ok thank you! :)
