### ISSUE TITLE
Problem with empty paragraphs

### ISSUE THREAD

**Issue by patrikengborg** [GetmeUK/ContentTools#363]
Hi,

First of all, thank you for an amazing library. I'm a bit blown away by the amount of work and attention to detail you have put in to this.

I have a problem that I don't really think is a bug, I probably use it the wrong way.

I want my users to land in edit mode right away, so after initializing the editor I enter edit mode with `editor.start()` and then hide the inspector with `editor._inspector.hide()`After that I populate my only region with `setContent()`. I also have a taint event for storing changes to localstorage. 

My problem is that every time i make an edit and then reload the page, an empty paragraph is added to the beginning of my region. If I make another edit and reload, another one is added. I tried to fix this with `createPlaceholderElement()`but without any luck.

So what am I doing wrong here? Is there any way to prevent the editor to add that empty paragraph? It probably is, but I can't find it in the documentation (which also is incredibly good by the way!)

Would really appreciate some pointers here. Thanks a lot!

**Comment by anthonyjb** [comment]
Hi @patrikengborg,

Thanks for the feedback - I checked out http://idnty.me/ yesterday and I loved the UI/UX of the site. In fact I loved the look of everything on the list on your idnty page!

With regard to the issue your trying to solve it sounds like when you start the editor it will initially see an empty region and by default that means it will create an empty paragraph. Since we want to disable this behaviour at least until you've set the content of the region you could set the private flag `editor._emptyRegionsAllowed` to `true` before you `start` the editor and then revert it back to `false` after calling `start`, e.g:

```JavaScript
editor._emptyRegionsAllowed = true;
editor.start();
editor.inspector().hide();        
editor._emptyRegionsAllowed = false;
```

Let me know how you get on, it that doesn't resolve the issue for you and you can provide a working code example I'll happily take a look and see if I can help out.

**Comment by patrikengborg** [comment]
Exactly something like that i was looking for, but couldn't find it. Thanks a lot!

I'm about to replace the Medium editor for Idnty. it's quite good but even that one adds a lot of <spans> and lineheight and crap. Content tools is the first one i've seen to get it right, plus the brilliant UI. Will let you know how it goes!

Thanks for a quick and detailed reply!
