### ISSUE TITLE
Pasting two lines doesn't replace selected text, is this normal behavior?

### ISSUE THREAD

**Issue by quiji** [GetmeUK/ContentTools#364]
You can try it on the demo site, just copy two or more lines of text and select a text to replace on the editor. When you paste it the selected text doesn't get replaced. The text just adds below.

**Comment by anthonyjb** [comment]
Hi @quiji - yes this is the expected behaviour - if you copy more than one line of content into the editor it will appended that content after the currently selected element.

Improved support for pasting HTML content in is on the list of things to to and we may improve this when we look at copy/paste against. In the meantime if you want to modify the behaviour you can do so by overriding paste method: https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/editor.coffee#L316

**Comment by quiji** [comment]
Thanks for the quick response!

I noticed there is a paste event. I wonder whats best: patch the paste method or catch the event and prevent bubbling up.. What do you suggest?

**Comment by anthonyjb** [comment]
@quiji I think I'd recommend clearing the paste event bindings (`ContentEdit.Root().unbind('paste')`) and then applying your own to handle the paste events. I thinks that's cleaner than patching the `ContentTools.EditorApp.paste` method personally.
