### ISSUE TITLE
How can I trigger a tool?

### ISSUE THREAD

**Issue by Tiseanu** [GetmeUK/ContentTools#383]
I'm trying to do something like this with jQuery: 
When I click on element (that i've created in DOM page) trigger video option.
$('#selector'.)click(function(){ $('div.ct-tool--video').click(); });

But it doesn't work.
Is there other way to trigger an option?

Many thanks,

**Comment by anthonyjb** [comment]
Hi @Tiseanu you can trigger tools by calling them directly with the element you want them to be triggered against. The approach you are taking isn't working because no editable element is selected and therefore the toolbox has most likely disabled the tool button.

To call the video tool directly you'd do something like:

```JavaScript
ContentTools.Tools.Video.apply(
    element, 
    null, 
    function (applied) { console.log('I was applied:', applied) } 
    );
```

The key here is you need to pass the editable element as the first argument to `apply`, this issue discusses a technique for selecting elements: https://github.com/GetmeUK/ContentTools/issues/381

**Comment by Tiseanu** [comment]
Hi Anthony,

Thank you so much for your answer and sorry to bother you again.
I added the code you gave me but it returns an error when insert the image:
Uncaught TypeError: insertNode.parent is not a function - And the pop-up seems to be triggered twice.

Thank you,
Tiseanu

**Comment by anthonyjb** [comment]
Hi @Tiseanu - can you provide your source, preferably in a jsfiddle or similar so I can take a look.

**Comment by Rocky89** [comment]
Hi Anthony,

I have the same issue here. I think you use something to transform that DOM element to some Text element.
Here is my code:
`$('div#buttons #btn').on("click", function(){
				var element = $('#edit_box p.ce-element--empty');
				ContentTools.Tools.Image.apply(
				  element,
				  null
				  );
			});`

Thanks in advance!

**Comment by anthonyjb** [comment]
@Rocky89 The element has to be an instance of a ContentEdit.Node or sub-class, the tool wont work on DOM element.
