### ISSUE TITLE
Run tests in PhantomJS

### ISSUE THREAD

**Issue by Svenskunganka** [GetmeUK/ContentTools#39]
Is there any reason tests are ran manually?

Adding [grunt-contrib-jasmine](https://github.com/gruntjs/grunt-contrib-jasmine) as a devDependency and a task to the Gruntfile will allow us to run the tests through PhantomJS. Could then hook up the tests and build process to Travis CI which is great because each commit in each PR will be tested.

If you want I can create a PR with updated Gruntfile and a `.travis.yml` configuration file.

**Comment by anthonyjb** [comment]
The only reason they are run manually is because I run them across each target browser using browser stack. Would still be good to automate against phantomjs and hook up to traviscli though, at least that way as you say each commit would be tested highlighting the majority of issues - so a PR for this would be great.

**Comment by anthonyjb** [comment]
I've implement this recommendation now - please note that for the ContentTools the test specification is not yet completed.
