### ISSUE TITLE
Remove unnecessary sentence from tutorial page list

### ISSUE THREAD

**Issue by cubiclesoft** [GetmeUK/ContentTools#396]
On the tutorial page:

http://getcontenttools.com/tutorials

Your second tutorial should just have the sentence, "A frank look at the dark side of in‑page editors."  And leave it at that.  There's really no need to be both vehement and offensive at the same time with the preceding sentence, which just detracts from the project.  It's also the only sentence like it on the tutorials page.

**Comment by anthonyjb** [comment]
I respectfully disagree :) 

Whilst I like to be concise when I write I also like to write in a conversational tone and often add in my own statements and thoughts as part of the text. CT is something I do because I enjoy writing software and giving back to the OS community, I don't intentionally set out to be offensive (I respect your right to be offended by the way), but in this case I don't see the issue and I like the article so I'm not going to change that part of it.

With regard to your other issue, I'll reply shortly in full but agree and I would like to provide additional examples for those using JavaScript. If you read through the several 100 issues I've replied to and my  stackoverflow answers you'll notice I provide JavaScript examples when asked to (which is far more often than CoffeeScript) so you may well find some pointers there - but ultimately I agree more JS in the tutorials would be advantageous for the majority of users and I'll consider that moving forward.

**Comment by cubiclesoft** [comment]
Okay.

The actual sentence that some will find offensive is, '"I _feckin' hate_ coding browser-based image uploading and editing tools" - A frank look at the dark side of in‑page editors.'  Emphasis mine.  The juxtaposition of that description compared to the rest of the tutorial descriptions seemed out of place.

At any rate, thanks for taking the time to respond.  I'll move on now.
