### ISSUE TITLE
On Paste trigger insert Image

### ISSUE THREAD

**Issue by Beludo** [GetmeUK/ContentTools#421]
Hello, 

I wanted to ask if there is any way when we paste a image from the clipboard, if it is possible to trigger the select image of the input file with the data url of the image pasted?

**Comment by anthonyjb** [comment]
Hi @Beludo,

It's certainly possible though it would require a completely different approach to the ImageUploadHandler, at the moment the example handlers are designed to call a remote interface (URL endpoints via HTTP).

The image dialog tool provided by the base ContentTools editor just calls triggers various events which the image handler listens and reacts to so if you used a library designed to handle data URL images (of which I believe there are many) to manage image upload and transformation within your image handler code it should just work. Effectively Instead of setting a remote URL in the image dialog you simply be setting a data URL.

Ant
