### ISSUE TITLE
Maths and chemical equations

### ISSUE THREAD

**Issue by imsiddharth** [GetmeUK/ContentTools#462]
Hi Anthony, the content tool is awesome.
I was looking for maths and chemical equation to add in content editor

<img width="336" alt="screen shot 2017-12-18 at 3 14 41 pm" src="https://user-images.githubusercontent.com/11020357/34103496-50c4549a-e406-11e7-9e9e-0908c384ffe6.png">

<img width="362" alt="screen shot 2017-12-18 at 3 14 47 pm" src="https://user-images.githubusercontent.com/11020357/34103506-5956859c-e406-11e7-9500-f1443b57f0e1.png">

i was not able to find the documentation for it. if you can guide me through it that would be helpfull.

Thanks,
Siddharth

**Comment by anthonyjb** [comment]
Hi @imsiddharth - thank you for the kind words!

I've not used equations with ContentTools before (or with HTML before) so I wasn't initially sure what to suggest. I've now had a play with a couple of libraries and as an initially suggestion before perhaps we integrate something fully I'd recommend looking at https://www.mathjax.org/

The library is easy to install and provides a way to convert a HTML shorthand (e.g `\(ax^2 + bx + c = 0\)`) to visual equation (as per your example).

As there's no integration with ContentTools (as of yet) what you'd need to do is use the MathJAX library on the public version of your pages (by including the script), but not use it in the editing environment (otherwise you'll end up storing the non-editable versions of the equations in your pages or database).

Longer term I'd like to look at maybe adding an extension so that the equations convert from/to and the HTML shorthand and visual equations when the editor is started and stopped.

Hope that helps - Ant
