### ISSUE TITLE
Q: What is the way to overwrite default CT methods by plugin system?

### ISSUE THREAD

**Issue by MalyshevDmitry** [GetmeUK/ContentTools#47]
I would like to make a plugin, which will overwrite paste() method in order to add opportunity to paste html data and clear it. Is it possible to do by developing plugin or something similar?

I know, that I can to overwrite method like:
```
editorCls = ContentTools.EditorApp.getCls()
editorCls.paste = (element, clipboardData) ->
    ... add you custom handler here ...
```

But it will be great, if CT will have plugin system to have opportunity make a public plugins for everyone.

**Comment by anthonyjb** [comment]
I agree a plugin guide would be a good idea, similar to how jQuery recommends creating plugins for their framework. 

Perhaps the library could do something similar to the image handler support, you could define a list of plugin functions against the ContentTools namespace that you want to use: 

    ContentTools.PLUGINS = [autoSort, htmlParse, ...] 

And then to initialize them you'd call a namespace method such as:

    ContentTools.initPlugins()

The `initPlugins` method would then call each plugin function. This allows plugins to be initialized in order and potentially to query which other plugins are supported (even if not yet initialized). It might be we insist on plugins being classes instead of functions and having a static name property so they can be identified.

Thoughts?

**Comment by concept-core** [comment]
@anthonyjb If this issue is done you can close it. ( as it give the feeling that there are a lot of issues ).
Also you closed the reference issue to.

**Comment by anthonyjb** [comment]
This isn't in place, I just lower on the priority list at the moment than number of issues (I don't mind lots of issues as long as there's not too many bugs).

**Comment by anthonyjb** [comment]
Discussion moved to issue https://github.com/GetmeUK/ContentTools/issues/237
