### ISSUE TITLE
How to create a composed element?

### ISSUE THREAD

**Issue by fernandofranca** [GetmeUK/ContentTools#50]
I'm trying want to create this simple Bootstrap panel as new tool:

```
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Panel title</h3>
  </div>
  <div class="panel-body">
    Panel content
  </div>
</div>
```

All this steps should be followed to create an editable/draggable element?
- Create a new class extending ContentEdit.ElementCollection
- Create a new class extending ContentTools.DialogUI (to add editable properties)
- Create a new class extending ContentTools.Tool

**Comment by anthonyjb** [comment]
Hi @fernandofranca, so I understand what you're attempting to do but I don't recommend this approach. Whilst it's possible, longer term I want to solve this type of problem in a different way. Instead of creating more complex editable elements the idea is to introduce the concept of flows and templates. 

Flows will allow users to add new sections of predefined HTML (templates)  to an existing HTML document. Templates can contain regions and therefore will allow the structure not just the content of the page to be edited, your example would therefore be converted to a template along the lines of:

```
<div class="panel panel-default" data-flow="well">
    <div class="panel-heading" data-editable="region-#?#">
        <h3 class="panel-title">Panel title</h3>
    </div>
    <div class="panel-body" data-editable="region-#?#">
        <p>Panel content</p>
    </div>
</div>
```

*`#?#` or something similar will be replaced automatically with a unique name for the region.*

The idea of using flows isn't original there's a number of in-context editors that take this approach, but I want it to be an optional extension to the library (probably named ContentFlows or similar) not a requirement. This is very much just a set of notes at the moment I have nothing concrete started but I wanted to let you know what the intention is moving forward.

Of course if you need to do this short term then you may need to settle on using a complex editable element instead in the mean time - I believe @bfintal has had some luck in doing this, if he has the time perhaps he might be able to provide a concrete example.

**Comment by fernandofranca** [comment]
Thanks for your careful response, Anthony!
It's nice to know that are intentions to improve ContentTools even more. It is quite promising.

I've tried to improvise a hacky approach by appending DOM elements by force, but without a deeper knowledge of the library it ends up breaking a lot of functionalities.

Thanks!!!

**Comment by Morganjackson** [comment]
ContentFlows sounds great, is it still planned?

**Comment by anthonyjb** [comment]
Hi @Morganjackson,

Yes support for adding dynamic editable regions (a la ContentFlows) is still very much on the board. We're currently working on a new web development framework/CMS (open source) which we're hoping to launch early-mid 2017, supporting for dynamic editable regions is (along with a number of other features) planned for the initial release of that project.
