### ISSUE TITLE
Q: Cannot read property 'descendants' of null

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#53]
I'm detaching an element with a click of a button. After detaching it, I'm getting this error:

    Uncaught TypeError: Cannot read property 'descendants' of null
        ContentTools.History.History._store	@	content-tools.js?ver=1.0:7657
        ContentTools.History.History.watch.delayedStore	@	content-tools.js?ver=1.0:7622

What is the right way to remove elements? I'm just doing an `element.parent().detach( element );`

**Comment by anthonyjb** [comment]
Blur the element before removing it permenantly, e.g:

    element.blur();
    element.parent().detatch(element);

I'll leave this issue open for now as history should check for this scenario, and possibly the default behaviour for detach should blur the element automatically. Will resolve early next week but that should fix the issue short term.

**Comment by bfintal** [comment]
Yup that fixes the problem. However, the error isn't really affecting the rest of the script so I'm just leaving it as is and just wait for the update :+1:

So before detaching, we should check first if the element being detached (or one of it's children) is focused and blur it first before proceeding.

Will see about putting a PR on this, but I'm focusing on other things right now :(

**Comment by anthonyjb** [comment]
It might not be as simple as it sounds to blur on detatch because when moving an element you may want it to retain focus - in fact I'm sure some of the code relies on this retained focus. You could refocus but that potential triggers a blur then trigger event that's perhaps unexpected as the focus hasn't moved from the element.

Perhaps I'll just add a check in history and add a note to the docs for detatch.

**Comment by anthonyjb** [comment]
@bfintal I believe I've fixed the issue you're experiencing by adding a check into the History._store method. 

However I'd recommend blurring the element you remove manually also. I'm don't want to add the automatically blurring behaviour I originally proposed as I feel this takes away a level of control that can (and currently is) useful.

**Comment by bfintal** [comment]
Thanks! What however would be a good use case for the manual blurring upon detachment? Just curious.

Because if the issue is with regards to the element being re-attached again after it got detached, then we could just keep note of the element which was auto-blurred then bring back the focus to it if it gets re-attached.

**Comment by anthonyjb** [comment]
Hi @bfintal the problem with auto blurring and then focusing when reattaching an element is that this triggers blur/focus events.

Triggering a blur/focus events on attach/detach could trigger different behaviour (such as removing a text element that's empty), a custom event binding could then cause issues when an element is drag/dropped for example and there would be no easy way for an external event binding to know if the element had been focused because it was reattached or because the user gave it focus.

One other thing to note is that if you auto blur then you will also  have manually focus when reattaching, we can't after all auto focus when attaching an element. So again in some circumstances we've just shifted the manual element somewhere else but we've lost control over when the events are triggered.
