### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by jnnkB** [GetmeUK/ContentTools#547]
Do you have any plan on when version 2.0 is going to be released?

**Comment by jnnkB** [comment]
I didn't wanted to seem write unfriendly and demanding (I hope thats the right word). I'm sorry if it seemed so. I just really enjoy building apps and editing text with ContentTools. Therefore I'm interested in the status of the library as I have to rewrite some parts of my software and therefore wanted to know whether I should wait for the new version of ContentTools.

Thanks a lot for your great work!

**Comment by anthonyjb** [comment]
@jnnkB sorry for the delayed reply, I'm planning on reviewing and answering some more issues this weekend so I'll be sure to respond to your query then. Your question wasn't received as rude at all, I should have responded sooner so my apologies for the tardiness.

**Comment by jnnkB** [comment]
Ok, then I'm glad I didn't seem impolite. Thanks for your fast response.

**Comment by anthonyjb** [comment]
Hi @jnnkB,

So I want to be as transparent as possible with regard to the future of the project and the development road map.

ContentTools is an important library for us as a company, we use it in a large number of client projects and it's a key feature of our in-house CMS application (manhattan). So CT isn't going to disappear or stop being supported anytime soon, however, as CT has been stable for a long time now we have been focusing our efforts on other projects for the last 3 years. In that time we've only made minor changes to CT most of which related to bug fixes or minor enhancements. The only significant development we made was the introduction of ContentFlow to manage layouts which was a key requirement of our CMS application. ContentFlow was a stop gap solution though and so it never got the documentation and attention required for a open source project.

We have over last 12 months moved all of our projects over to use ES6 and webpack, and so CoffeeScript and Grunt aren't part of our pipeline anymore, this means it's becoming more pressing for us to redevelop ContentTools and the associated libraries so that we can more easily support them.

Redeveloping ContentTools is a big commitment and we have a lot of features and changes we'd like to add/make as part of that process. I don't have any definite dates for the redevelopment but it is now a priority for us to start this process and move away from CoffeeScript (which I love but which no longer has a place IMHO), my expectation is that we will start this project this year and I estimate it will take me between 6-12 months to get to a release 2.0.

What I am going to do shortly is create a new github project for release 2.0 to allow developers currently using CT to discuss features they most want to see. I'll leave a link to the new repo on the current repo's homepage as soon as it's up.

**Comment by jnnkB** [comment]
Hi,

Thanks for your reply. Did I understand it right, that you're going to use something different than ContentFlow to manage blocks in the future? Do you already know whether it's going to be an open source library?

**Comment by anthonyjb** [comment]
There will continue to be a layout library but it will be part of the standard ContentTools library rather than an after thought.

CT will always be open source :)

**Comment by jnnkB** [comment]
OK, that sounds cool.
