### ISSUE TITLE
Enhance table handling

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#62]
I think the table behavior can be improved:
- When the table gets blurred, remove empty rows
- When hitting the backspace / shift-tab on the first cell & first column of an empty row, remove the empty row
- ~~On mouse down for a long time on the table should drag the whole table~~

**Comment by anthonyjb** [comment]
Can you confirm that holding the mouse down for a longer time doesn't work for you. That behaviour is already in place and works for me currently - however could be there's a problem in a specific browser.

With regard to removing empty rows when they're blurred I don't see any reason not too.

**Comment by bfintal** [comment]
I have not noticed that when you hold the mouse longer it turned into a table drag. Alright, never mind that :+1:

**Comment by anthonyjb** [comment]
@bfintal @Qqwy OK so I've pushed an update that implements the second suggestion...

> When hitting the backspace / shift-tab on the first cell & first column of an empty row, remove the empty row

...but not the first. Deleting all empty rows on blur didn't end up feeling as intuitive as I expected, for one copying into a table from the document becomes hard because creating a new row then selecting text from the page removes the new row.

I have however put in place support for empty rows using the delete key however, so if the row is empty and you press the delete key with any table cell selected the row will be removed. This makes it much easier navigate through and delete empty rows.

We're further looking at table behaviour in a new issue #152 posted by @Qqwy which has some additional suggestions we might try, so for now I'm closing this issue and suggest any further conversation is moved to the new issue.
