### ISSUE TITLE
Add tool apply events

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#66]
This would be very helpful for triggering code for when the content is manipulated, including undos, redos and deletions (since doing a shortcut e.g. undo triggers the undo tool)

**Comment by MalyshevDmitry** [comment]
:+1:

**Comment by anthonyjb** [comment]
Make sense.

I think we may run into the same complications discussed for adding start/stop events #31 - that the event system needs to be overhauled for ContentTools. I'm considering switching to native events but support seems to be sketch at the moment so I'd need to use deprecated interfaces to support for the target browser list currently.

**Comment by bfintal** [comment]
Native events are fine, but I don't think it's a required change. For me the main benefit would be a shorter syntax with `editor.addEventListener`, but aside from that, I don't see any other benefits (let me know if there are others, I'm not a Javascript guru).

Why overhaul the event system?

**Comment by anthonyjb** [comment]
The ToolUI components now trigger `apply` and `applied` events (http://getcontenttools.com/api/content-tools#tool-ui) so it is possible to listen for these events now in the toolbox using:

```
editor.toolbox()._toolUIs['bold'].addEventListener('apply', function (ev) { ... });
```

So you can monitor the tools applied by the user and/or changes to the region (using ContentEdit events), what you can't do yet is bind events to the Tool static classes at this time (because they don't inherit from the ComponentUI class). However I'm intending to review this for the next release along with adding additional events now the new event model is in place so this discussion will move to a new issue.
