### ISSUE TITLE
Adding links to partially formatted text splits the link

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#80]
If you select the following text inside a paragraph:

    <b>I'm bold</b> I'm not

Then turn that in a link, the link gets split into half:

    <b><a href='#'>I'm bold</a></b> <a href='#'>I'm not</a>

I think the ideal behavior should be this so that the text remains a single link:

    <a href='#'><b>I'm bold</b> I'm not</a>

You can try this in the demo page. It works correctly if you select these, the unwanted behavior only happens if the tag is at the start:

    I'm not bold <b>I'm bold</b>

or

    I'm not bold <b>I'm bold</b> I'm not

**Comment by anthonyjb** [comment]
I agree this would be better behaviour for links. I think this can be fixed if I ensure that `<a>` tags are added as the first tag in the stack (perhaps HTMLString.format could accept a flag to allow you to indicate you want a tag added at the start of the stack).

**Comment by anthonyjb** [comment]
OK so I've reviewed this issue fully now and actually it's not the whole story, so the behaviour described is as stated and the reason for this is that form performance reasons strings of HTML aren't optimized when operations are performed on them, that optimization (using `optimize`) happens when the string of HTML is saved.

So actually if you then save the page (in my tests at least), since optimized is called the HTML that's output to the `save` event appears as `<a href='#'><b>I'm bold</b> I'm not</a>`.

I'm not 100% sure if the fact the HTML is not optimzed after the link tag is insert is potentially an issue or not but it seems safer to simply call `optimize` against the content when an in-line tag is inserted using one of the tools and so this is the change I have made.
