### ISSUE TITLE
Disable element key handler temporally 

### ISSUE THREAD

**Issue by Eeliya** [GetmeUK/ContentTools#84]
Hi, 

I add a input tag to some of my paragraph with a specific attribute and with the added input I want to edit the value of that attribute.

But even when I am on the input, the parent paragraph still capture key events like backspace or enter.

Is there any way to disable the element key handler temporally?

**Comment by anthonyjb** [comment]
Hi @Eeliya, my recommendation here would be to prevent `keydown` events propagating from your input to the `contenteditable` parent (e.g the paragraph). To do this you'll need to ensure that you bind event listeners to your `input` elements whenever they are created since the process of converting them to editable content will replace them they will loose any associated event listeners.

One approach you might consider *(this code should be applied before setting up the editor)*:

```JavaScript1
// Listen for elements being mounted
ContentEdit.Root.get().bind('mount', function (element) {
    var i, inputs;

    // We're only interested in elements that support content
    if (element.content === undefined) {
        return;
    }

    // Search for inputs within the newely mounted element
    inputs = element.domElement().querySelectorAll('input');
    for (i = 0; i < inputs.length; i++) {
        // Prevent the propagation of the `keydown` event to the parent of the input 
        inputs[i].addEventListener('keydown', function (ev) {
            ev.stopPropagation();
        });
    }
});
```

I hope that proves helpful - let me know how you get on.

**Comment by Eeliya** [comment]
Thanks for your solution. It worked! :)

I was trying to bind mount event after initialization, but that did not work. As you said it should be applied before setting up the editor.

**Comment by Eeliya** [comment]
One issue. This approach does not seem to work if I add input to a element on the fly. 

For example I add a input tag to paragraph when it is selected and key event still traverse from input to the paragraph.

I solved this by adding the input into the ct-app like modals and dialog and set its position to the corresponding element position. it's a bit tricky but it works in my case.

**Comment by anthonyjb** [comment]
Cool - glad you found a work around
