### ISSUE TITLE
Request: region ready event

### ISSUE THREAD

**Issue by Eeliya** [GetmeUK/ContentTools#85]
It would be great to get an `region-ready` event when region is done with parsing the HTML.

At the moment I added `ContentEdit.Root.get().trigger('region-ready', this)` at the end of Region constructor.

**Comment by anthonyjb** [comment]
I think an event triggered at the end of construction of a `ContentEdit.Region` is a good idea - however if there are multiple regions then I presume you'd want an event once all regions had been parsed - which would be a ContentTools event rather than a ContentEdit event - and comes back https://github.com/GetmeUK/ContentTools/issues/31.

**Comment by Eeliya** [comment]
In my case I only need event for Region ready. I only have one Region at the time.

**Comment by anthonyjb** [comment]
This event is now part of the core ContentEdit library, documented here: http://getcontenttools.com/api/content-edit#events
