### ISSUE TITLE
Make a tag invisible to ContentEdit

### ISSUE THREAD

**Issue by Eeliya** [GetmeUK/ContentTools#86]
I want to show some information or inline tools in some elements as sub elements.

I can do this by registering an mount event listener and then add my custom stuff. But they should be **invisible** to ContentEdit and `html()` method of element should **NOT** include them.

I have read about Static elements but I don't think that is what I want.

One solution that I came up with was to add right click popup, but that does not give me the UI/UX  that I want.

What would be a good solution in this case?

**Comment by anthonyjb** [comment]
So a number of the editable elements already do this type of thing (e.g Video and Image), this is done by having `mount()` do one thing and `html()` do another.

The best approach will be to override the `html` and `mount` methods against the class that you want to add this behaviour to (e.g `ContentEdit.Text` - I'm assuming this is at least one of the elements you want to customize). Remember though that behaviour is inherited so if that's a problem you may want to consider inheriting from the class instead and replace it in the tags names:

```coffeescript
class MyNewElement extends ContentEdit.Text

    # My custom text elemment
    ...

# Associate my new class with all text elements
ContentEdit.TagNames.get().register(
    MyNewElement,
    'address',
    'blockquote',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'p'
    )
```

Whether you override just the methods or the entire class you will need to change `mount`'s behaviour to output more than `html`. For example if you're just looking to display information then you might consider the approach taken by images for size, here a `data-...` attribute is set against the element when mounted and that information is then displayed using a `:before` pseudo element and the CSS `content: attr(data-...);` rule, the attribute is not stored in the list of attributes for the element so on output `html` does not include this attribute. 

If you need something more complex than this you will most likely need to mount additional DOM elements, and if so you'll also need to look at modifying the `_syncContent` method so that instead of the entire content of the text element being selected using `this._domElement.innerHTML` that any additional nodes mounted are excluded.

I hope this sets you in the right direction, I'm happy to provide more guidance but a concrete example of what you're attempting to do would be useful in providing more specific advice.

**Comment by Eeliya** [comment]
![EW editor based on ContentEdit](https://drive.google.com/uc?export=view&id=0BzdHnrSRsU85RE1KQ0t1c080a2c)

As you can see in the image, the control bar at top of my elements is not inside that element, its over it and I align them via javascript. it works fine but having them inside their corresponded element itself would be much better.

Now I should keep them visually and logically in sync (which I don't think is a good solution). I want to add other tools into that bar as well. Tools that are provided by the CMS.

So if there was an API that could give me the ability to add inline toolbar (or I would call it shadow element) to a element but never get included in html, then that would be more than great.

*The image you see is a screenshot of the content form of my CMS*

**Comment by anthonyjb** [comment]
OK so support for attaching the toolbar to the current selected region has been suggested before and I think it will be a necessary task when we move to mobile, however I don't think I'd look to inline the toolbar inside the content itself, I think I'd do as you are doing now and use JavaScript to keep it's position and size in sync. Whilst this is more effort for the browser it's cleaner IMHO as it keeps ContentTools and ContentEdit decoupled. ContentEdit shouldn't need to know how to handle a ContentTools toolbar ideally.

**Comment by Eeliya** [comment]
Ok, so I will try to optimize my code to increase performance.

Thank you :)
